#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2011 Christopher Bratusek		#
#							#
#########################################################

wizard_start ()
{

	whiptail --title $"BashStyle-NG $BSNG_VERSION First-Run-Wizard" --msgbox "This wizard will guide you through fully setting up your copy
of BashStyle-NG to be able to make use of all shipped functions." 12 85
}

wizard_end ()
{
	whiptail --title $"BashStyle-NG $BSNG_VERSION First-Run-Wizard" --msgbox $"You just finished generating your configuration.
You can find it in $HOME/.bashstyle.wizard. You may re-run this wizard via bs-ng-wizard --force. \
To see a list of usefull tips for the bash, run bashtips." 12 85

}


wizard_base ()
{

	whiptail --title $"verbosity" --yesno $"Do you want to disable the text flying by, when starting bash?" 12 85

	if [[ $? == "0" ]]; then
		wizard_set debug_verbose False
	else	wizard_set debug_verbose True
	fi

	whiptail --title $"restore" --yesno $"Do you want to restore the last working directory when starting bash?" 12 85

	if [[ $? == "0" ]]; then
		wizard_set restore_directory True
	else	wizard_set restore_directory False
	fi

	whiptail --title $"colorshell" --yesno $"Do you want to use colorshell (different text color after each command)?" 12 85

	if [[ $? == "0" ]]; then
		wizard_set color_shell True
	else	wizard_set color_shell False
	fi

}
