#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

wizard_cdwriter_one ()
{
	whiptail --title $"Writer device" --yesno $"The writeiso and geniso functions need to know what device to access.
By default /dev/dvdrw is beeing used, do you want to choose a different device?" 12 85

	if [[ $? == "0" ]]; then
		xcdwriter=$(whiptail --title "set CD_WRITER" --inputbox "Enter the devicenode of your CD/DVD-Writer:" 12 85 "$CD_WRITER" 3>&1 1>&2 2>&3)
		rc_add export CD_WRITER=\"$xcdwriter\"
	fi

	whiptail --title $"geniso error tolerance" --yesno $"By default geniso stops at the first read error.
Do you want geniso to continue anyways? [recommended]" 12 85

	if [[ $? == "0" ]]; then
		rc_add export DD_OPTS=\"conv=noerror\"
	fi
}
