#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2012 Christopher Bratusek		#
#							#
#########################################################

wizard_cdwriter ()
{
	whiptail --title $"Writer device" --yesno $"The writeiso and geniso functions need to know what device to access.
By default /dev/dvdrw is beeing used, do you want to choose a different device?" 12 85

	if [[ $? == "0" ]]; then
		xcdwriter=$(whiptail --title "set CD_WRITER" --inputbox "Enter the devicenode of your CD/DVD-Writer:" 12 85 "$(wizard_get cd_writer)" 3>&1 1>&2 2>&3)
		wizard_set cd_writer $xcdwriter
	fi

	whiptail --title $"geniso error tolerance" --yesno $"By default geniso stops at the first read error.
Do you want geniso to continue anyways? [recommended]" 12 85

	if [[ $? == "0" ]]; then
		wizard_set dd_noerror True
	else	wizard_set dd_noerror False
	fi
}
