#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

wizard_get ()
{

	sed -n "s/^${1} = \(.*$\)/\1/p" $HOME/.bs-ng-wizard.ini | sed -e 's/\"//g'

}

wizard_set ()
{

	SETTING=${1}
	shift
	VALUE=${@}

	sed -e "s+^${SETTING} = .*$+${SETTING} = ${VALUE}+" -i $HOME/.bs-ng-wizard.ini

}
