#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

wizard_reprepro ()
{
	whiptail --title $"reprepro setup" --yesno $"Do you want to setup reprepro?
If you have a repo managed via reprepro, you can now setup repoadd." 12 85

	if [[ $? == "0" ]]; then
		repo_home=$(whiptail --title $"reprepro repo home" --inputbox $"Enter the full path to the repo base directory:" 12 85 "$(wizard_get repo_home)" 3>&1 1>&2 2>&3)
		wizard_set repo_home $repo_home

		repo_dist=$(whiptail --title $"reprepro repo dist" --inputbox $"Enter the name of the default dist:" 12 85 "$(wizard_get repo_dist)" 3>&1 1>&2 2>&3)
		wizard_set repo_dist $repo_dist
	fi
}
