#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2011 Christopher Bratusek		#
#							#
#########################################################

wizard_svn_accounts ()
{

	whiptail --title $"svn.enlightenment.org" --yesno $"Do you have an Enlightenment SVN account?
With this info get_e can checkout SVN repos with write access." 12 85

		if [[ $? == "0" ]]; then
			get_e_user=$(whiptail --title $"svn.enlightenment.org account" --inputbox $"What's your Enlightenment SVN Account?:" 12 85 "$(wizard_get e_vcs_user)" 3>&1 1>&2 2>&3)
			wizard_set e_vcs_user $get_e_user
		fi
}
