#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

update_wizard_2 () {

	whiptail --title $"BashStyle-NG $BSNG_VERSION First-Run-Wizard" --msgbox "In Version 8.3 of BashStyle-NG new questions have been added to the wizard." 12 85

	# this part updates the ini file
	sed -e 's/ini_version.*/ini_version = 2/g' -i $HOME/.bs-ng-wizard.ini
	line=$(($(grep -wnm 1 color_shell ~/.bs-ng-wizard.ini | sed -e 's/:.*//')+1))
	sed -i "${line}icolor_shell_reset = False" $HOME/.bs-ng-wizard.ini

	whiptail --title $"colorshell" --yesno $"Do you want colorshell to return to default text-color when executing a command (don't recolor command output)?" 12 85

	if [[ $? == "0" ]]; then
		wizard_set color_shell_reset True
	else	wizard_set color_shell_reset False
	fi

	whiptail --title $"BashStyle-NG $BSNG_VERSION First-Run-Wizard" --msgbox $"You just finished updating your configuration." 12 85
}
