#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

case $1 in

	--help | -h | "")
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "box" -s "create a boxes around text" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "text:|text to place inside the box"
	;;

	* )	t="$1xxxx";c=${2:-#};
		echo "${t//?/$c}
$c $1 $c
${t//?/$c}"
	;;

esac
