#!/bin/bash
#
# by goelztec
# from: https://www.commandlinefu.com/commands/view/25663/
#

shopt -s extdebug
declare -F | grep -v "declare -f _" | declare -F $(awk "{print $3}") | column -t
shopt -u extdebug

