#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

check P "ps2pdf" "man2pdf" || exit 1

man_exists () {
	man -t "${1}" &>/dev/null

	# 'man' returns 16, if a manpage does not exist
	if [[ $? -ne 0 ]]; then
		return 1
	else	return 0
	fi
}

case ${1} in
	--help | -h | "")
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
			-l "GNU GPL v3" -n "man2pdf" -s "$(eval_gettext "create PDF from a manpage")"\
			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "$(eval_gettext "manpage:bash|manpage to create a PDF from")"
	;;

	* )
		manpage="${1}"

		man_exists "${manpage}" && man -t "${manpage}" | ps2pdf - > "${manpage}.pdf" \
			|| echo "$(eval_gettext "manpage ${manpage} does not exist")"
	;;
esac

