#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright Christopher Bratusek			#
#							#
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

case ${1} in
	--help | -h | "")
		bashstyle-help -a "flatcap" -e "" -h "http://www.commandlinefu.com/"\
				-l "Public Domain" -n "psgrep" -s "$(eval_gettext "find process by name")"\
				-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
				-o "$(eval_gettext "name:|find process by name")"
	;;

	* )
		ps aux | grep -v psgrep | grep -E "[${1:0:1}]${1:1}|^USER"
	;;
esac
