#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

. gettext.sh
TEXTDOMAIN="bashstyle-rc"

case ${1} in
	--help | -h | "")
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
			-l "GNU GPL v3" -n "round" -s $"round number" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o $"number:|number to round"\
			-o $"decimal places:|(optional) decimal places [or 0]"
	;;

	* )
		if [ ! -z  "${2}" ]; then
			printf "%.${2}f\n" "${1}"
		else	printf "%.0f\n" "${1}"
		fi
	;;
esac

unset TEXTDOMAIN
