#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

case ${1} in
	-h | --help )
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
			-l "GNU GPL v3" -n "showuser" -s "$(eval_gettext "prompt function to display $ or user-set char, or # for root")"\
			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "$(eval_gettext "none:|---")"
	;;

	*)
		if [[ ${EUID} -eq 0 ]]; then
			echo -e "${ered}#"
		elif [[ ! -z ${user_char} ]]; then
			echo -e "${ecolor_user}${user_char}"
		else	echo -e "${ecolor_user}$"
		fi
	;;
esac
