#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright Christopher Bratusek			#
#							#
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

case ${1} in
	-h | --help )
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
			-l "GNU GPL v3" -n "stopwatch" -s "$(eval_gettext "a simple stopwatch")"\
			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "$(eval_gettext "none:|--")"
	;;

	*)
		BEGIN=$(date +%s)

		while true; do
			NOW=$(date +%s)
			DIFF=$((NOW-BEGIN))
			MINS=$((DIFF/60))
			SECS=$((DIFF%60))
			echo -ne "$(eval_gettext "Time elapsed:")" "${MINS}:$(printf %02d ${SECS})\r"
			sleep .1
		done
	;;
esac
