#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

dep="xmlindent"
prog="xmlpager"
if ! which ${dep} &>/dev/null; then
	eval_gettext "${dep} not found, ${prog} won't work."; echo
	exit 1
fi

case ${1} in
	-h | --help )
		bashstyle-help -a "hackerb9" -e "" -h "http://www.commandlinefu.com/"\
			-l "GNU GPL v3" -n "xmlpager" -s "$(eval_gettext "pager for xml files with highlighted text")"\
			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "$(eval_gettext "file:|xml file to read")"
	;;

	*)
		xmlindent "${@}" | \
			awk '{gsub(">",">'$(tput bold; tput setf 4)'"); gsub("<","'$(tput sgr0)'<"); print;} END {print "'$(tput sgr0)'"}' | \
			less -r
	;;
esac
