#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek    	#
# Copyright 2008        Ayo                             #
#							#
#########################################################

user="whoami"
host=$(echo -n $HOSTNAME | sed -e "s/[\.].*//")

function pre_prompt {

newPWD="${PWD}"
datenow=$(date "+%a, %d %b %y")
let promptsize=$(echo -n "--( $user @ $host ddd., DD mmm YY )( ${PWD} )--" | wc -c | tr -d " ")

let fillsize=${COLUMNS}-${promptsize}

fill=""
while [ "$fillsize" -gt "0" ]
do
    fill="${fill}─"
	let fillsize=${fillsize}-1
done
if [ "$fillsize" -lt "0" ]
then
    let cutt=3-${fillsize}
    newPWD="...$(echo -n $PWD | sed -e \"s/\(^.\{$cutt\}\)\(.*\)/\2/\")"
fi

if [[ $enabcol == true ]]; then
  PRE_PROMPT_COMMAND
fi

}

PROMPT_COMMAND=pre_prompt

if [[ $enabcol == true ]]; then

        PS1="$sepacolor┌─($usercolor \u$fontcolor @ $hostcolor\h\
$datecolor \$(date \"+%a, %d %b %y\")$sepacolor )─\${fill}─($wdircolor \$newPWD \
$sepacolor)─<\n$sepacolor└─($timecolor \$(date \"+%H:%M\")$usercolor \$$sepacolor )─>$fontcolor "

else    PS1="┌─( \u @ \h \$(date \"+%a, %d %b %y\") )─\${fill}─( \$newPWD \
)─<\n└─( \$(date \"+%H:%M\") \$ )─> "

fi
