#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

if [[ $enabcol == true ]]; then

PS1="\n$pscolor≺ ⁐ ⊐$usercolor \u$fontcolor  $hostcolor\h $pscolor⊏ ⁐ ≻
$fontcolor $wdircolor\$(trunc_pwd) $fontcolor "

else

PS1="\n≺ ⁐ ⊐ \u  \h ⊏ ⁐ ≻\n \$(trunc_pwd)  "

fi
