#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG 7.10				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

if [[ $enabcol == true ]]; then

PS1="\n\[\033[37;41;1m\]\u @ \h \[\033[37;40;1m\] $datecolor\d $timecolor\$(date +%I:%M:%S%P)\n$wdircolor\$(trunc_pwd)$fontcolor $ "

else

PS1="\n\u @ \h \d \$(date +%I:%M:%S%P)\n\$(trunc_pwd) $ "

fi
