#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2011 Christopher Bratusek		#
#							#
#########################################################

export pstyle_supported=true

if [[ $enabcol == "True" ]]; then

PS1="\n\
$pscolor┌─$sepacolor[ $wdircolor\$(trunc_pwd)$DIRKS_1_COLOR\$(DIRKS_1) $sepacolor]\n\
$pscolor└─$sepacolor[ $usercolor\u $fontcolor@ $hostcolor\H $fontcolor/ $pscolor\$(show_tty) $sepacolor( $timecolor\t $sepacolor) $pscolor$SHLVL$DIRKS_2_COLOR\$(DIRKS_2) $sepacolor]$pscolor·>$fontcolor "

else

PS1="\n\
┌─[ \$(trunc_pwd)\$(DIRKS_1) ]\n\
└─[ \u @ \H / \$(show_tty) ( \t ) $SHLVL\$(DIRKS_2) ]·> "

fi
