#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

export truncpwd_supported=True

if [[ ${enable_colors} == True ]]; then

PS1="\n${pscolor}.:${sepacolor}[ ${usercolor}\u${pscolor} @ ${hostcolor}\h${sepacolor} ]${pscolor}:. .:${sepacolor}[ ${wdircolor}\$(truncpwd)${sepacolor} ]${pscolor}:.\n.:${sepacolor}[·>${fontcolor} "

else

PS1="\n.:[ \u @ \h ]:. .:[ \$(truncpwd) ]:.\n.:[·> "

fi
