#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ ${enable_colors} == True ]]; then

PS1="\n\
${pscolor}┌─${sepacolor}[ ${usercolor}\u ${fontcolor}@ ${hostcolor}\h${sepacolor} ]${pscolor}─\
${sepacolor}[${pscolor} job #\# ${sepacolor}]${pscolor}─${sepacolor}[${fontcolor} \$(systemkit tty)${sepacolor} ]\
${pscolor}─${sepacolor}[ ${timecolor}\$(date +%H:%M:%S)\
${fontcolor} : ${datecolor}\$(date +%m/%d/%y)${fontcolor} :${upcolor} \$(systemkit uptime)${sepacolor} ]\n\
${pscolor}└─${sepacolor}[ ${usercolor}\$${pscolor} : ${wdircolor}\$(truncpwd)${ELITE_1_COLOR}\$(ELITE_1)${sepacolor} ]\
${pscolor}·>${fontcolor} "

else

PS1="\n\
┌─[ \u @ \h ]─[ job #\# ]─[ \$(systemkit tty) ]─[ \$(date +%H:%M:%S)\
: \$(date +%m/%d/%y) : \$(systemkit uptime) ]\n└─[ \$ : \$(truncpwd)\$(ELITE_1) ]·> "

fi
