#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2016 Christopher Bratusek		#
#							#
#########################################################

host=${HOSTNAME/.*}

# make the prompt properly re-draw when pressing [Return]
bind 'RETURN: "\C-l\C-j"'

function pre_prompt {

local j=4
local k=6
local l=8
local m=10
local n=12

[[ ! ${dirchar} ]] && dirchar="/"
[[ ! ${trunc_symbol} ]] && trunc_symbol="«"
[[ ! ${trunc_length} ]] && trunc_length=1

newPWD="${PWD}"

let promptsize=$(echo -n "--( $(whoami) @ ${host} )--( ${PWD} )-----" | wc -c | tr -d " ")

let fillsize=${COLUMNS}-${promptsize}
fill=""
while [ "${fillsize}" -gt "0" ]
do
    fill="${fill}─"
	let fillsize=${fillsize}-1
done

if [ "${fillsize}" -lt "0" ]
then
    let cutt=${trunc_length}-${fillsize}
    xPWD="${trunc_symbol}${PWD:${cutt}}"
    newPWD="${xPWD//\//${ecolor_separator}${dirchar}${ecolor_wdir}}"
else
    newPWD="${PWD//\//${ecolor_separator}${dirchar}${ecolor_wdir}}"
fi

_newPWD () {
	echo -e $newPWD
}

echo -en "\033[2;$((${COLUMNS}-29))H"
echo -en "${ecolor_separator}(${ecolor_time} $(date +%H:%M)${ecolor_separator} :${ecolor_date} $(date '+%a, %d %b %y')${ecolor_separator} )────┐"
echo -en "\033[3;${COLUMNS}H${ecolor_separator}│"

i=${LINES}

[[ ${i} -ge 16 ]] && while [ ${i} -ge 4 ]
do
	case ${i} in
		${j} )
			echo -en "\033[${j};$((${COLUMNS}-29))H"
			echo -en "${ecolor_separator}(${ecolor_font} system-load: $(systemkit load1)${ecolor_separator} )────────┤"
		;;
		${k} )
			echo -en "\033[${k};$((${COLUMNS}-29))H"
			echo -en "${ecolor_separator}(${ecolor_font} cpu-load: $(systemkit cpuload)${ecolor_separator} )────────────┤"
		;;
		${l} )
			echo -en "\033[${l};$((${COLUMNS}-29))H"
			echo -en "${ecolor_separator}(${ecolor_font} ram: ${ecolor_separator}$(systemkit usedram)mb${ecolor_font} / ${ecolor_separator}$(systemkit freeram)mb )─────┤"
		;;
		${m} )
			echo -en "\033[${m};$((${COLUMNS}-29))H"
			echo -en "${ecolor_separator}(${ecolor_font} processes:${ecolor_ps} $(systemkit processes) ${ecolor_separator})──────────┤"
		;;
		${n} )
			echo -en "\033[${n};$((${COLUMNS}-29))H"
			if [ ${lastexit} -eq 0 ]; then
				echo -en "${ecolor_separator}( ${egreen}✔: ${lastcommandprintable} ${ecolor_separator})─┤"
			else
				echo -en "${ecolor_separator}( ${ered}✘: ${lastcommandprintable} ${ecolor_separator})─┤"
			fi
		;;
		* )
			echo -en "\033[$((${i}));${COLUMNS}H${ecolor_separator}│"
		;;
	esac
	let i=${i}-1
done

let prompt_line=${LINES}-1
}

PROMPT_COMMAND=pre_prompt

PS1="\[\033[\${prompt_line};0H\]\n\
${color_separator}┌─( ${color_user}\u ${color_font}@ ${color_host}\h \
${color_separator})─\${fill}─( ${color_wdir}\$(_newPWD)\
${color_separator} )────┘\n\
${color_separator}└─(${color_uptime} uptime: \$(systemkit uptime)\
${color_font} :${EQUINOX_1_COLOR}\$(EQUINOX_1)${color_font} \$ ${color_separator})·>${color_font} "
