#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

if [[ $enabcol == true ]]; then

PS1="\n$sepacolor[ $timecolor\t$sepacolor ] $usercolor\u $wdircolor\$(trunc_pwd)$pscolor \$$fontcolor "

else

PS1="\n[ \t ] \u \$(trunc_pwd) $ "

fi
