#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

SEPA_1 () { return 0; }
SEPA_2 () { return 0; }

VECTOR_1 () { return 0; }
VECTOR_2 () { return 0; }

CLOCK_1 () { return 0; }

CLOCK_AD_1 () { return 0; }

ELITE_1 () { return 0; }

POW_1 () { return 0; }

DIRKS_1 () { return 0; }
DIRKS_2 () { return 0; }

SEPA_NG_1 () { return 0; }

QUIRK_1 () { return 0; }

PRE_PROMPT_COMMAND () { return 0; }