#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ $enabcol == "True" ]]; then

PS1="\n$sepacolor -$pscolor( $usercolor\u$sepacolor /$hostcolor \h$pscolor )$sepacolor-$pscolor( \$(systemkit tty) )$sepacolor-$pscolor($upcolor uptime: \$(systemkit uptime)$pscolor )$sepacolor-$pscolor($timecolor \$(date +%H:%M)$datecolor \$(date +%d-%b-%y)$pscolor )$sepacolor-$pscolor($wdircolor files: \$(systemkit countvisiblefiles)$sepacolor /$wdircolor folders: \$(systemkit countvisibledirs)$pscolor )$sepacolor-\n -$pscolor<$wdircolor \$(truncpwd)$QUIRK_1_COLOR\$(QUIRK_1) $pscolor>$sepacolor-$fontcolor "

else

PS1="\n -( \u / \h )-( \$(systemkit tty) )-( uptime: \$(systemkit uptime) )-( \$(date +%H:%M) \$(date +%d-%b-%y ) )-( files: \$(systemkit countvisiblefiles) / folders: \$(systemkit countvisibledirs) )-\n -< \$(truncpwd)\$(QUIRK_1) >- "

fi
