#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ $enable_colors == "True" ]]; then

PS1="\n$sepacolor⊏⁅ $usercolor\u$pscolor ⁑ $hostcolor\h $sepacolor⁆⁅ $datecolor\d $pscolor⁑ $timecolor\t$pscolor ⁑ $upcolor\$(systemkit uptime)$sepacolor ⁆⊐
⊏⁅$wdircolor \$(truncpwd)$SEPA_NG_1_COLOR\$(SEPA_NG_1) $sepacolor⁆⊐≻$fontcolor "

else

PS1="\n⊏⁅ \u ⁑ \h ⁆⁅ \d ⁑ \t ⁑ \$(systemkit uptime) ⁆⊐\n⊏⁅ \$(truncpwd)\$(SEPA_NG_1) ⁆⊐≻ "

fi
