#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

sepa=$(ini_get separator)
export pstyle_supported=True

if [[ $enabcol == "True" ]]; then

	PS1="\n$usercolor\u$fontcolor @$hostcolor \h$sepacolor $sepa $datecolor\d$sepacolor $sepa $timecolor\t$sepacolor $sepa $wdircolor\$(truncpwd)"
	[[ $(ini_get files_amount) == "True" ]] && PS1+=" files: \$(count_files -f)"
	[[ $(ini_get files_amount) == "True" && $(ini_get file_size) == "True" ]] && PS1+="$sepacolor /"
	[[ $(ini_get file_size) == "True" ]] && PS1+="$wdircolor size: \$(show_size)"
	[[ $(ini_get tty) == "True" ]] && PS1+=" $sepacolor$sepa$hostcolor tty: \$(show_tty)"
	[[ $(ini_get uptimes) == "True" ]] && PS1+=" $sepacolor$sepa$upcolor uptime: \$(show_uptime)"
	[[ $(ini_get load) == "True" ]] && PS1+=" $sepacolor$sepa$upcolor system load: \$(show_system_load)"
	[[ $(ini_get processes) == "True" ]] && PS1+=" $sepacolor$sepa$pscolor processes: \$(count_processes)"
	[[ $(ini_get battery_load) == "True" ]] && PS1+=" $sepacolor$sepa$pscolor battery: \$(show_battery_load)"
	[[ $(ini_get mem) == free ]] && PS1+=" $sepacolor$sepa$usercolor free mem: $pscolor\$(show_mem --free)$usercolor mb"
	[[ $(ini_get mem) == used ]] && PS1+=" $sepacolor$sepa$usercolor used mem: $pscolor\$(show_mem --used)$usercolor mb"
	[[ $(ini_get mem) == both ]] && PS1+=" $sepacolor$sepa$usercolor free$sepacolor/${usercolor}used mem: $pscolor\$(show_mem --free)$sepacolor/$pscolor\$(show_mem --used)$usercolor mb"
	PS1+="$sepacolor $sepa\n$usercolor$SEPA_1_COLOR\$(SEPA_1)\$ $SEPA_2_COLOR\$(SEPA_2)$fontcolor-> "

else

	PS1="\n\u @ \h $sepa \d $sepa \t $sepa \$(truncpwd)"
	[[ $(ini_get files_amount) == "True" ]] && PS1+=" files: \$(count_files -f)"
	[[ $(ini_get files_amount) == "True" && $(ini_get file_size) == "True" ]] && PS1+="$sepacolor /"
	[[ $(ini_get file_size) == "True" ]] && PS1+=" size: \$(show_size)"
	[[ $(ini_get tty) == "True" ]] && PS1+=" $sepa tty: \$(show_tty)"
	[[ $(ini_get uptimes) == "True" ]] && PS1+=" $sepa uptime: \$(show_uptime)"
	[[ $(ini_get load) == "True" ]] && PS1+=" $sepa system load: \$(show_system_load)"
	[[ $(ini_get processes) == "True" ]] && PS1+=" $sepa processes: \$(count_processes)"
	[[ $(ini_get battery_load) == "True" ]] && PS1+=" $sepa battery: \$(show_battery_load)"
	[[ $(ini_get mem) == free ]] && PS1+=" $sepa free mem: \$(show_mem --free) mb"
	[[ $(ini_get mem) == used ]] && PS1+=" $sepa used mem: \$(show_mem --used) mb"
	[[ $(ini_get mem) == both ]] && PS1+=" $sepa free/used mem: \$(show_mem --free)/\$(show_mem --used) mb"
	PS1+=" $sepa\n\$ -> "

fi
