#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

export pstyle_supported=True

if [[ $enable_colors ==  true ]]; then

PS1="\n$pscolor♦$sepacolor♦($usercolor \u$fontcolor @$hostcolor \h $fontcolor: Space on /: $pscolor\$(systemkit usedspace /)$fontcolor used of$pscolor \$(systemkit totalspace /)$sepacolor )♦♦($wdircolor \$(truncpwd)$sepacolor )♦$pscolor♦\n\
$pscolor♦$sepacolor♦($timecolor \$(date +%H:%M)$sepacolor →$datecolor \$(date \"+%a, %d %b %y\")$sepacolor : uptime :$upcolor \$(systemkit uptime)$sepacolor :$usercolor \$$sepacolor )♦$pscolor♦$fontcolor "

else

PS1="\n♦♦( \u @ \h : Space on /: \$(systemkit usedspace /) used of \$(systemkit totalspace /) )♦♦( \$(truncpwd) )♦♦\n\
♦♦( \$(date +%H:%M) → \$(date \"+%a, %d %b %y\") : uptime : \$(systemkit uptime) \$ )♦♦ "

fi

