#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ $enabcol == "True" ]]; then

PS1="\n$pscolor┌$sepacolor($usercolor \u$sepacolor @ $hostcolor\h \
$sepacolor)$pscolor─$sepacolor( $timecolor\$(date +%I:%M%P)$VECTOR_1_COLOR\$(VECTOR_1)\
$fontcolor -:- $datecolor\$(date +%m)/\$(date +%d)$sepacolor )\n\
$pscolor└$sepacolor( $wdircolor\$(truncpwd) $VECTOR_2_COLOR\$(VECTOR_2)$sepacolor)$pscolor·>$fontcolor "

else

PS1="\n┌( \u @ \h )─( \$(date +%I:%M%P)\
-:- \$(date +%m)/\$(date +%d) )\$(VECTOR_1)\n\
└( \$(truncpwd) \$(VECTOR_2))·> "

fi
