#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

BASH_KEYS=( cdpath colored_grep colored_ls colored_man custom_command custom_prompt \
debug debug_log debug_verbose dirchar fcedit fignore hist_control hist_ignore history_size \
man_style path prompt_style ps234 pwdchar pwdmaxlength random_style tabrotate timeout \
use_bashstyle use_custom_prompt welcome_message )

ALIAS_KEYS=( alias/one alias/two alias/three alias/four alias/five alias/six alias/seven \
alias/eight alias/nine)

COLOR_KEYS=( color/style color/date color/font color/grep color/host color/ps234c \
color/separatorc color/time color/uptime color/enable color/user color/wdir )

DIRCOLOR_KEYS=( dircolors/custom dircolors/deb dircolors/dirs dircolors/enable dircolors/exec \
dircolors/flac dircolors/generic dircolors/gif dircolors/jpeg dircolors/logs dircolors/mp3 dircolors/ogg \
dircolors/png dircolors/rar dircolors/rpm dircolors/tar dircolors/tarbz2 dircolors/targz dircolors/zip )

SEPARATOR_KEYS=( separator/battery_load separator/files_amount separator/file_size separator/load \
separator/mem separator/processes separator/tty separator/uptimes separator/separator )

READLINE_KEYS=( readline/ambiguous readline/bellstyle readline/completion readline/completionhz \
readline/editing_mode readline/hidden readline/ignore_case readline/mark_dirs readline/mark_modlines \
readline/mark_sym_dirs readline/query_item readline/scrollhz readline/use_readlinecfg readline/vstats )

SHOPT_KEYS=( shopt/autocd shopt/cdable_vars shopt/cdspell shopt/checkhash shopt/checkjobs shopt/cmdhist \
shopt/dirspell shopt/force_fignore shopt/globstar shopt/histappend shopt/histreedit shopt/no_empty_cmd_completion )

VIM_KEYS=( vim/autosave vim/backup vim/dark_background vim/filetype_indent vim/highlight vim/hl_cursor \
vim/ignore_case vim/inc_search vim/jump_back vim/number vim/ruler vim/rulerformat vim/show_cmd vim/show_match \
 vim/smart_case vim/syntax_hilight vim/use_vimcfg vim/vim_colorscheme )

NANO_KEYS=( nano/auto_indent nano/backup nano/bold_text nano/case_sensitive nano/const nano/more_space \
nano/nohelp nano/use_colors nano/use_nanocfg nano/history nano/rebind_del nano/rebind_kp )
