#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

assign() {
	for opt in "${@}"; do
		var="X=\$${opt/:*}"
		eval "${var}"
		[[ ${X} == "" ]] && read -r "${opt/:*}" <<< "${opt/*:}"
	done
}

ini_get ()
{
	sed -n "s/^${1} = \(.*$\)/\1/p" "${HOME}"/.bs-ng.ini | sed -e 's/\"//g'
}

def_get ()
{
	sed -n "s/^${1} = \(.*$\)/\1/p" \
		"${BSNG_DATADIR}"/bashstyle-ng/bs-ng.ini | \
		sed -e 's/\"//g'
}

ven_get ()
{
	[[ -f /etc/bs-ng_vendor.ini ]] && sed -n "s/^${1} = \(.*$\)/\1/p" \
		/etc/bs-ng_vendor.in | sed -e 's/\"//g'
}

ini_set ()
{
	SETTING=${1}
	shift
	VALUE="${*}"

	sed -e "s/^${SETTING} = .*$/${SETTING} = ${VALUE}/" -i "${HOME}"/.bs-ng.ini
}

ini_add ()
{
	SECTION=${1}
	shift
	VALUE="${*}"

	sed -e "/\[${SECTION}\]/ a ${VALUE}" -i "${HOME}"/.bs-ng.ini
}

rc_add ()
{
	dbg_msg "$@"
	echo "${@}" >> "${RC_FILE}"
}
