#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

ini_get ()
{

	sed -n "s/^${1} = \(.*$\)/\1/p" $HOME/.bs-ng.ini | sed -e 's/\"//g'

}

ini_set ()
{

	SETTING=${1}
	shift
	VALUE=${@}

	sed -e "s/^${SETTING} = .*$/${SETTING} = ${VALUE}/" -i $HOME/bs-ng.ini

}

ini_add ()
{

	SECTION=${1}
	shift
	VALUE=${@}

	sed -e "/\[${SECTION}\]/ a ${VALUE}" $HOME/.bs-ng.ini

}

rc_add ()
{

	echo "$@" >> $RC_FILE

}

check_opt() {

	APP="$1"
	which "$APP" &>/dev/null

	if (( $? != 0 )); then
		shift
		echo -e "$APP not found!\n\`$@' won't work without it."
		return 1
	fi
}
