#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

check_opt mencoder any2avi

MENC_OPTS="-lavdopts threads=8 -ovc xvid -xvidencopts fixed_quant=4 -of avi -oac mp3lame -lameopts vbr=3"

case ${1} in

	--help | -h )

		bsng-help -a "Christopher Roy Bratusek" -e "nano@tuxfamily.org" -h "http://www.nanolx.org/"\
				-l "GNU GPL v3" -n "any2avi" -s "convert any mencoder supported" -v "2" -y "2013"\
				-o "input:|convert video to Avi (xvid + lame)"

	;;

	* )

		for vid in "${@}"; do
			mencoder "${vid}" ${MENC_OPTS} -o "${vid}".avi
		done

	;;
esac