#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")

		bsng-help -a "Christopher Roy Bratusek" -e "nano@tuxfamily.org" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "asc2all" -s "convert ascii char to numerical equivalent" -v "${BSNG_VERSION}" -y "2011"\
			-o "letter:|convert ascii char to numerical equivalent"

	;;

	* )
		echo "ascii $1 = binary $(asc2bin $1)
ascii $1 = octal $(asc2oct $1)
ascii $1 = decimal $(asc2dec $1)
ascii $1 = hexadecimal $(asc2hex $1)
ascii $1 = base32 $(asc2b32 $1)
ascii $1 = base64 $(asc2b64 $1)"
	;;
esac