#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 ]]; then
	echo "ascii $1 = binary $(asc2bin $1)"
	echo "ascii $1 = octal $(asc2oct $1)"
	echo "ascii $1 = decimal $(asc2dec $1)"
	echo "ascii $1 = hexadecimal $(asc2hex $1)"
	echo "ascii $1 = base32 $(asc2b32 $1)"
	echo "ascii $1 = base64 $(asc2b64 $1)"
fi
