#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")

		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "asc2dec" -s "convert ascii char to decimal equivalent" -v "${BSNG_VERSION}" -y "2007-2013"\
			-o "letter:|convert ascii char to decimal equivalent"

	;;

	* )
		printf '%d\n' "'$1'"
	;;
esac