#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")

		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "asc2oct" -s "convert ascii char to octal equivalent" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "letter:|convert ascii char to octal equivalent"

	;;

	* )
		echo "obase=8 ; $(asc2dec $1)" | bc
	;;
esac