#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

for opt in $@; do
	var="X=\$${opt/:*}"
	eval $var
	if [[ $X == "" ]]; then
		read ${opt/:*} <<< $(echo ${opt/*:})
	fi
done
