#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 ]]; then
	echo "binary $1 = octal $(bin2oct $1)"
	echo "binary $1 = decimal $(bin2dec $1)"
	echo "binary $1 = hexadecimal $(bin2hex $1)"
	echo "binary $1 = base32 $(bin2b32 $1)"
	echo "binary $1 = base64 $(bin2b64 $1)"
	echo "binary $1 = ascii $(bin2asc $1)"
fi
