#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

case $1 in

	--help | -h | "")

		bsng-help -a "Christopher Roy Bratusek" -e "nano@tuxfamily.org" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "bin2all" -s "convert binaries to other numeric equivalents" -v "${BSNG_VERSION}" -y "2013"\
			-o "number:|convert binary to other numeric equivalents"

	;;

	* )
		echo "binary $1 = octal $(bin2oct $1)
binary $1 = decimal $(bin2dec $1)
binary $1 = hexadecimal $(bin2hex $1)
binary $1 = base32 $(bin2b32 $1)
binary $1 = base64 $(bin2b64 $1)
binary $1 = ascii $(bin2asc $1)"
	;;
esac