#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "bin2b64" -s "convert binaries to base64" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "number:|convert binary to base64"
	;;

	*) 	echo "obase=64 ; ibase=2 ; $1" | bc ;;

esac
