#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

bookmark () {

	if [[ $(grep go-$1= $HOME/.bookmarks) == "" ]]; then
		echo "alias go-$1='cd $PWD'" >> $HOME/.bookmarks
		. $HOME/.bookmarks
	else	echo "bookmark go-$1 already exists."
	fi

}

unmark () {

	if [[ $(grep $1= $HOME/.bookmarks) != "" ]]; then
		sed -e "/$1/d" -i $HOME/.bookmarks
		xunalias $1
	fi

}
