#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 != "" && $(alias | grep -w go-$1) == "" ]]; then
	echo "alias go-$1='cd $PWD'" >> $HOME/.bookmarks
	. $HOME/.bookmarks
elif [[ $1 == "" ]]; then
	echo "need name for the bookmark."
else	echo "bookmark go-$1 already exists."
fi
