#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

t="$1xxxx";c=${2:-#};
echo ${t//?/$c};
echo "$c $1 $c";
echo ${t//?/$c};
