#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG 7.10				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

bs_ng_echo_help()
{
	echo -e "\nSyntax: echo -e '\$(bs_ng_echo <color>) text'"
	echo -e "\nPossible values for <color>:"
	echo -e "\n$(echo $white | sed -e 's/\\\[//g' -e 's/\\\]//g')\$white\
	\n$(echo $blue | sed -e 's/\\\[//g' -e 's/\\\]//g')\$blue\
	\n$(echo $red | sed -e 's/\\\[//g' -e 's/\\\]//g')\$red\
	\n$(echo $green | sed -e 's/\\\[//g' -e 's/\\\]//g')\$green\
	\n$(echo $yellow | sed -e 's/\\\[//g' -e 's/\\\]//g')\$yellow\
	\n$(echo $cyan | sed -e 's/\\\[//g' -e 's/\\\]//g')\$cyan\
	\n$(echo $black | sed -e 's/\\\[//g' -e 's/\\\]//g')\$black\
	\n$(echo $coldblue | sed -e 's/\\\[//g' -e 's/\\\]//g')\$coldblue\
	\n$(echo $iceblue | sed -e 's/\\\[//g' -e 's/\\\]//g')\$iceblue\
	\n$(echo $smoothblue | sed -e 's/\\\[//g' -e 's/\\\]//g')\$smoothblue\
	\n$(echo $smoothgreen | sed -e 's/\\\[//g' -e 's/\\\]//g')\$smoothgreen\
	\n$(echo $magenta | sed -e 's/\\\[//g' -e 's/\\\]//g')\$magenta\
	\n$(echo $turqoise | sed -e 's/\\\[//g' -e 's/\\\]//g')\$turqoise\
	\n$(echo $winered | sed -e 's/\\\[//g' -e 's/\\\]//g')\$winered\
	\n$(echo $brown | sed -e 's/\\\[//g' -e 's/\\\]//g')\$brown\
	\n$(echo $silver | sed -e 's/\\\[//g' -e 's/\\\]//g')\$silver\
	\n$(echo $ocher | sed -e 's/\\\[//g' -e 's/\\\]//g')\$ocher\
	\n$(echo $orange | sed -e 's/\\\[//g' -e 's/\\\]//g')\$orange\
	\n$(echo $purple | sed -e 's/\\\[//g' -e 's/\\\]//g')\$purple\
	\n$(echo $pink | sed -e 's/\\\[//g' -e 's/\\\]//g')\$pink\
	\n$(echo $cream | sed -e 's/\\\[//g' -e 's/\\\]//g')\$cream\n"
	tput sgr0
}

bs_ng_echo ()
{

	case $1 in

		*help )
			bs_ng_echo_help
		;;

		* )
			if [[ $enabcol == "true" ]]; then
				echo $1 | sed -e 's/\\\[//g' -e 's/\\\]//g'
			fi
		;;

	esac

}
