#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h)
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "cel2fah" -s "convert °C to °F" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "number:|convert °C to °F"
	;;

	* )
		echo "scale=2; $1 * 1.8  + 32" | bc
	;;
esac
