#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

check_opt() {

	which $1 &>/dev/null
	if (( $? != 0 )); then
		echo -e "$1 not found!\n$2 won't work without it."
		exit 1
	fi
}
