#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2016 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h)
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "clock" -s "simple clock for bash" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "none:|--"
	;;

	*)
		while true; do
			clear;
			echo "===========";
			date +"%r";
			echo "===========";
			sleep 1;
		done
	;;

esac
