#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
# Copyright 2006 Philip Endecott			#
#							#
#########################################################

if [[ $enabcol == "True" ]]; then

	cmd_text_colour=`tput setaf $((RANDOM%7))`

	shopt -s promptvars

	PS1="${PS1}${cmd_text_colour}"
	PS2="${PS2}${cmd_text_colour}"
	PS3="${PS3}${cmd_text_colour}"
	PS4="${PS4}${cmd_text_colour}"

fi
