#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in
	*+h)
		echo $(($(ls --color=no -1 -la . | grep -v ^l | wc -l)-1))
	;;

	*-h)
		echo $(($(ls --color=no -1 -l . | grep -v ^l | wc -l)-1))
	;;

	*+f)
		echo $(($(ls --color=no -1 -la . | grep -v ^- | wc -l)-1))
	;;

	*-f)
		echo $(($(ls --color=no -1 -l . | grep -v ^- | wc -l)-1))
	;;

	*+d)
		echo $(($(ls --color=no -1 -la . | grep -v ^d | wc -l)-1))
	;;

	*-d)
		echo $(($(ls --color=no -1 -l . | grep -v ^d | wc -l)-1))
	;;

	*)
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "count_files" -s "count files in current directory " -v "${BSNG_VERSION}"\
			-y "${BSNG_YEAR}"\
			-o "+h:|count files and folders (include hidden)"\
			-o "-h:|count files and folders (exclude hidden)"\
			-o "+d:|count folders only (include hidden)"\
			-o "-d:|count folders only (exclude hidden)"\
			-o "+f:|count files only (include hidden)"\
			-o "-f:|count files only (exclude hidden)"
	;;
esac
