#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

case $1 in
	*+h)
		echo $(($(ls --color=no -1 -la . | grep -v ^l | wc -l)-1))
	;;

	*-h)
		echo $(($(ls --color=no -1 -l . | grep -v ^l | wc -l)-1))
	;;

	*+d)
		echo $(($(ls --color=no -1 -la . | grep -v ^- | wc -l)-1))
	;;

	*-d)
		echo $(($(ls --color=no -1 -l . | grep -v ^- | wc -l)-1))
	;;

	*+f)
		echo $(($(ls --color=no -1 -la . | grep -v ^d | wc -l)-1))
	;;

	*-f)
		echo $(($(ls --color=no -1 -l . | grep -v ^d | wc -l)-1))
	;;

	*)
		echo -e "\n${ewhite}Usage:"
		echo -e "\n${eorange}count_files${ewhite} | ${egreen}+h ${eiceblue}[count files and folders - include hidden ones] \
		\n${eorange}count_files${ewhite} | ${egreen}-h ${eiceblue}[count files and folders - exclude hidden ones] \
		\n${eorange}count_files${ewhite} | ${egreen}+d ${eiceblue}[count folders - include hidden ones] \
		\n${eorange}count_files${ewhite} | ${egreen}-d ${eiceblue}[count folders - exclude hidden ones] \
		\n${eorange}count_files${ewhite} | ${egreen}+f ${eiceblue}[count files - include hidden ones] \
		\n${eorange}count_files${ewhite} | ${egreen}-f ${eiceblue}[count files - exclude hidden ones]\n"
		tput sgr0
	;;
esac
