#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	*help | -h)
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "count_processes" -s "count running processes" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "none:|--"
	;;

	* )
		procs=$(ps ax | wc -l | awk '{print $1}')

		if [[ $procs -lt 10 ]]; then
			echo "000$procs"
		elif [[ $procs -lt 100 ]]; then
			echo "00$procs"
		elif [[ $procs -lt 1000 ]]; then
			echo "0$procs"
		fi
	;;
esac
