#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2017 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "crypt" -s "crypt input string by shift 13 (also known as ceasars code)"\
			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "text:|text to crypt"
	;;

	*)
		echo "${@}" | tr a-zA-Z n-za-mN-ZA-M
	;;

esac
