#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

if [[ -e "$1" ]]; then
	tr a-zA-Z n-za-mN-ZA-M < "$1" > "$1".crypt
	rm -f "$1"
	mv "$1".crypt "$1"
fi
