#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "d2u" -s "convert DOS to Unix line endings" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "files:|file to convert"
	;;

	*)
		for file in "${@}"; do
			[[ -f "${1}" ]] && sed -r 's/\r$//' -i "$1"
		done
	;;

esac
