#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 ]]; then
	echo "decimal $1 = binary $(dec2bin $1)"
	echo "decimal $1 = octal $(dec2oct $1)"
	echo "decimal $1 = hexadecimal $(dec2hex $1)"
	echo "decimal $1 = base32 $(dec2b32 $1)"
	echo "decimal $1 = base64 $(dec2b64 $1)"
	echo "deciaml $1 = ascii $(dec2asc $1)"
fi
