#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "dec2oct" -s "convert decimal to octal" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "number:|convert number to octal"
	;;

	*)
		echo "obase=8 ; $1" | bc
	;;

esac
