#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################


case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "dec2asc" -s "convert decimal to ascii char" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "number:|convert number to ascii char"
	;;

	*)
		echo -e "\0$(printf %o 97)"
	;;

esac
