#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

dirinfo () {

	case $1 in

		*help | "")
			$BSNG_RC_DIR/dirinfo/index --help
		;;

		*create)
			$BSNG_RC_DIR/dirinfo/create
		;;

		*)
			$BSNG_RC_DIR/dirinfo/index "$@"
		;;

	esac

}

lscd () {

	builtin cd "${@}" &>/dev/null
	$BSNG_RC_DIR/dirinfo/display

	echo -e "${epink}content:"
	ls $LSCD_OPTS
	echo "$PWD" > $HOME/.lastpwd

}
