#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

dirinfo_get_creation_date () {

	if [[ ! "$1" ]]; then
		DIR="."
	else	DIR="$1"
	fi

	if [[ -d "$DIR" ]]; then
		stat "$DIR" | grep "Modify" | gawk '{print $2}'
	fi

}

dirinfo_set_creation_date () {

	if [[ ! "$1" ]]; then
		DIR="."
	else	DIR="$1"
	fi

	if [[ -e "$DIR"/.dirinfo ]]; then
		sed -e '/Created/d' -i "$DIR"/.dirinfo
		echo "Created=$(dirinfo_get_creation_date $DIR)" >> "$DIR"/.dirinfo
	fi

}

dirinfo_get_dirinfo () {

	if [[ ! "$1" ]]; then
		DIR="."
	else	DIR="$1"
	fi

	if [[ -e "$DIR"/.dirinfo ]]; then
		. "$DIR"/.dirinfo
	fi

	echo -e "\n${eyellow} -- $PWD --${ewhite}"

	if [[ ! ${Type} ]]; then
		dirinfo_display_info
	else	dirinfo_display_ascii
	fi

	unset Owner Created Allow Delete Tags Notes Type ASCII
	echo ""

}

dirinfo_display_info () {

	if [[ ${Owner} ]]; then
		echo -e "\n${eiceblue}\tOwner:   ${Owner}"
	fi

	if [[ ${Created} ]]; then
		echo -e "${emagenta}\tCreated: ${Created}"
	fi

	if [[ ${Tags} ]]; then
		echo -e "${ered}\tTags:    ${Tags[@]}"
	fi

	if [[ ${Notes} ]]; then
		echo -e "\n${egreen} ${Notes}"
	fi

}

dirinfo_display_ascii () {

	if [[ -e $BSNG_RC_DIR/ascii/folder-${Type} ]]; then
		ASCII="$BSNG_RC_DIR/ascii/folder-${Type}"
	elif [[ -e $DIR/.dirascii ]]; then
		ASCII="$DIR/.dirascii"
	fi

	if [[ $ASCII ]]; then
		echo -e "$(cat $ASCII)" | sed -e "s/@OWNER@/${Owner}/g" \
			-e "s/@CREATED@/${Created}/g" \
			-e "s/@TAGS@/${Tags[*]}/g" \
			-e "s/@NOTES@/${Notes}/g"
	else 	unset Type
		dirinfo_display_info
	fi

}

dirinfo_index_db () {

	find $HOME -name .dirinfo | grep -w .dirinfo > $HOME/.dirinfo_index

}

dirinfo_index_tags () {

	if [[ -e $HOME/.dirinfo_index ]]; then
		for dirinfo in $(cat $HOME/.dirinfo_index); do
			echo "${dirinfo%.dirinfo}" :: $(grep Tags "$dirinfo") > $HOME/.dirinfo_tags
		done
		sed -e 's/Tags=(//' -e 's/)//g' -i $HOME/.dirinfo_tags
	fi

}

dirinfo_search () {

	case $1 in
		*tags)
			grep -w "$2" $HOME/.dirinfo_tags | gawk '{print $1}'
		;;
	esac

}
