#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

d2u () {

	if [[ -e "$1" ]]; then
		sed -r 's/\r$//' -i "$1"
	fi

}

u2d () {

	if [[ -e "$1" ]]; then
		sed -r 's/$/\r/' -i "$1"
	fi

}
