#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2017 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h)
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "empty" -s "find empty files" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "directory:|(optional) find empty files in directory (or current)"
	;;

	*)
		find "$1" -empty
	;;

esac
