#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

typeset temp
SAVE=$IFS
IFS=''
eval $(echo "temp=\"\$$1\"")
eval $(echo "$1=\"\$$2\"")
eval $(echo "$2=\"$temp\"")
IFS=$SAVE
