#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

get_key ()
{

	if [[ ! $BSNG_GCONF_READ ]]; then
		gconftool-2 --get $1
	else	gconftool-2 --get /apps/bashstyle/$1
	fi

}

set_key ()
{

	if [[ ! $BSNG_GCONF_READ ]]; then
		gconftool-2 --set --type $1 $2 $3
	else	gconftool-2 --set --type $1 /apps/bashstyle/$2 $3
	fi

}

reset_key ()
{

	if [[ ! $BSNG_GCONF_READ ]]; then
		gconftool-2 --unset $1
	else	gconftool-2 --unset /apps/bashstyle/$1
	fi

}

reset_config ()
{

	gconftool-2 --recursive-unset /apps/bashstyle/

}

search_key () {

	gconftool-2 --search-key $1

}
