#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ $CD_WRITER ]]; then
	dd $DD_OPTS if=$CD_WRITER of="$1"
else	dd $DD_OPTS if=/dev/dvdrw of="$1"
fi
