#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

git_export() {

	if [[ $1 != "" ]]; then
		git checkout-index --prefix=$1/ -a
	fi

}

git_bzip() {

	git archive master | bzip2 -9 >$PWD.tar.bz2

}

git_xz() {

	git archive master | xz -9 > $PWD.tar.xz

}

get_gnome () {

	if [[ $1 == "-m" ]]; then
		git clone git+ssh://$2@git.gnome.org/git/$3
	elif [[ $1 == "-b" ]]; then
		git clone -b $2 git://git.gnome.org/$3
	else 	git clone git://git.gnome.org/$1
	fi
}

get_xfce () {

	if [[ $1 == "-b" ]]; then
		git clone -b $2 git://git.xfce.org/category/$3
	else	git clone git://git.xfce.org/category/$1
	fi

}
