#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ -d .git ]]; then
	git archive master | xz -9 > "$PWD".tar.xz
else	echo "current directory is not the root of a git repository"
fi
