#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ -d .git ]]; then
	git rev-list --reverse HEAD | \
		awk "/$(git log -n 1 --pretty="format:%h")/ {print NR}"
else	echo --
fi
