#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

if [[ -d .git ]]; then
	BRANCH=$(git symbolic-ref HEAD 2>/dev/null)
	echo ${BRANCH#refs/heads/}
else	echo --
fi
