#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

if [[ -d .git ]]; then
	REVISION=$(git rev-parse HEAD 2>/dev/null)
	REVISION=${REVISION/HEAD/}
	echo ${REVISION:0:6}
else	echo --
fi
