#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 ]]; then
	echo "hexadecimal $1 = binary $(hex2bin $1)"
	echo "hexadecimal $1 = octal $(hex2oct $1)"
	echo "hexadecimal $1 = decimal $(hex2dec $1)"
	echo "hexadecimal $1 = base32 $(hex2b32 $1)"
	echo "hexadecimal $1 = base64 $(hex2b64 $1)"
	echo "hexadecimal $1 = ascii $(hex2asc $1)"
fi
