#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
				-l "GNU GPL v3" -n "hex2all" -s "convert hexadecimal to other numerical equivalents" \
				-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
				-o "hexadecimal:|number to convert"
	;;

	*)
		echo "hexadecimal $1 = binary $(hex2bin $1)
hexadecimal $1 = octal $(hex2oct $1)
hexadecimal $1 = decimal $(hex2dec $1)
hexadecimal $1 = base32 $(hex2b32 $1)
hexadecimal $1 = base64 $(hex2b64 $1)
hexadecimal $1 = ascii $(hex2asc $1)"
	;;

esac
