#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

RET=$(dirinfo --search -jump "$1")
if [[ -d "$(echo ${RET/ */})" ]]; then
	lscd $(dirinfo --search -jump "$1")
else
	echo "No directory with mark \"$1\" found."
fi
