#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "jump" -s "jump to a directory know to dirinfo" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "mark:|jump mark to follow"
	;;

	* )
		RET=$(dirinfo --search -jump "$1")
		if [[ -d "$(echo ${RET/ */})" ]]; then
			lscd $(dirinfo --search -jump "$1")
		else
			echo "No directory with mark \"$1\" found."
		fi
	;;

esac
