#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "kel2cel" -s "convert °K to °C" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "number:|convert °K to °C"
	;;

	* )
		echo "scale=2; $1 - 273.15" | bc
	;;

esac
