#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################


case ${1} in

	--help | -h)
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "l1" -s "one-column ls, directories first " -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "directory:|(optional) director [or current]"
	;;

	* )
		ls -1 --group-directories-first "$@"
	;;

esac
