#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

if [[ "$@" == "" ]]; then
	$@="*"
fi

ls -l --group-directories-first "$@" | gawk '{print $9, "belongs to Group ->", $4}' | column -t
