#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h)
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "lm" -s "print plain-text and octal permissons of files" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "directory:|(optional) directory [or current]"
	;;

	* )
		find -maxdepth 1 -printf "Permissons of %f -> %M (%m)\n" | column -t
	;;

esac
