#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ ${1} && ${2} ]]; then
	for dir in ${1//:/ }; do
		if [[ -e ${dir}/${2} ]]; then
			echo ${dir}/${2} && continue 2
		fi
	done
fi
