#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

clear
builtin cd "${@}" &>/dev/null
. $BSNG_RC_DIR/dirinfo/display
dirinfo_display

echo -e "${epink}content:\n"
if [[ $(count_files -h) -gt 0 ]]; then
	ls $LSCD_OPTS
else	echo -e "${ecream}-- empty --\n"
fi
echo "$PWD" > $HOME/.lastpwd
