#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

source $BSNG_RC_DIR/internal/misc

case $1 in
	*help | "" )
		echo -e "\n${ewhite}Usage:"
		echo -e	"\n${eorange}man2pdf${ewhite} |${egreen} <manualpage>${eiceblue} [generate a pdf from <manualpage>]\n"
		tput sgr0
	;;

	* )
		check_opt ps2pdf man2pdf
		if [[ $? != "1"  && $1 ]]; then
			man -t $1 | ps2pdf - >$1.pdf
		else	echo "No manpage given."
		fi
	;;
esac
