#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [ $# -lt 2 ] || [[ ! "$@" =~ :[[:space:]] ]];then
	echo "Invalid syntax." >&2; return 1
fi

until [[ $1 =~ : ]]; do
	command="$command $1"; shift
done

command="$command ${1%:}"; shift
for i in "$@"; do
	eval "${command//\\/\\\\} \"${i//\\/\\\\}\""
done
