#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

top10 () {

	history | awk '{print $2}' |\
	awk 'BEGIN {FS="|"}{print $1}' |\
	sort | uniq -c | sort -n | tail | sort -nr

}

crypt () {

	if [[ -e $1 ]]; then
		tr a-zA-Z n-za-mN-ZA-M < $1 > $1.crypt
		rm -f $1
		mv $1.crypt $1
	fi

}

d2u () {

	if [[ -e $1 ]]; then
		sed -r 's/\r$//' -i $1
	fi

}

u2d () {

	if [[ -e $1 ]]; then
		sed -r 's/$/\r/' -i $1
	fi

}
