#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

top10 () {

	history | awk '{print $2}' |\
	awk 'BEGIN {FS="|"}{print $1}' |\
	sort | uniq -c | sort -n | tail | sort -nr

}

crypt () {

	if [[ -e $1 ]]; then
		tr a-zA-Z n-za-mN-ZA-M < $1 > $1.crypt
		rm -f $1
		mv $1.crypt $1
	fi

}

d2u () {

	if [[ -e $1 ]]; then
		sed -r 's/\r$//' -i $1
	fi

}

u2d () {

	if [[ -e $1 ]]; then
		sed -r 's/$/\r/' -i $1
	fi

}

torswitch () {

	if ! [[ $EUID == 0 ]]; then
		exit 1
	fi

	case $1 in
		*on )
			if [[ $(grep forward-socks4a /etc/privoxy/config) == "" ]]; then
				echo "forward-socks4a / 127.0.0.1:9050 ." >> /etc/privoxy/config
			else
				sed -e 's/\# forward-socks4a/forward-socks4a/g' -i /etc/privoxy/config
				/etc/init.d/tor restart
				/etc/init.d/privoxy restart
			fi
		;;

		*off )
			sed -e 's/forward-socks4a/\# forward-socks4a/g' -i /etc/privoxy/config
			/etc/init.d/tor restart
			/etc/init.d/privoxy restart
		;;
	esac

}

repoadd () {

	reprepro -Vb $1 include $2 *.changes
	cd $1/dists/$2
	gpg -abs -o Release.gpg Release

}

get_kernel () {

	if [[ $1 == "-s" ]]; then
		wget http://www.kernel.org/pub/linux/kernel/v2.6/linux-${2}.tar.bz2
	elif [[ $1 == "-t" ]]; then
		wget http://www.kernel.org/pub/linux/kernel/v2.6/testing/linux-${2}.tar.bz2
	elif [[ $1 == "-sg" ]]; then
		git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-${2}.y.git
	elif [[ $1 == "-tg" ]]; then
		git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux-2.6.git
	fi

}
