#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

top10 () {

	history | awk '{print $2}' |\
	awk 'BEGIN {FS="|"}{print $1}' |\
	sort | uniq -c | sort -n | tail | sort -nr

}

crypt () {

	if [[ -e $1 ]]; then
		tr a-zA-Z n-za-mN-ZA-M < $1 > $1.crypt
		rm -f $1
		mv $1.crypt $1
	fi

}

d2u () {

	if [[ -e $1 ]]; then
		sed -r 's/\r$//' -i $1
	fi

}

u2d () {

	if [[ -e $1 ]]; then
		sed -r 's/$/\r/' -i $1
	fi

}

torswitch () {

	if ! [[ $EUID == 0 ]]; then
		exit 1
	fi

	case $1 in
		*on )
			if [[ $(grep forward-socks4a /etc/privoxy/config) == "" ]]; then
				echo "forward-socks4a / 127.0.0.1:9050 ." >> /etc/privoxy/config
			else
				sed -e 's/\# forward-socks4a/forward-socks4a/g' -i /etc/privoxy/config
				/etc/init.d/tor restart
				/etc/init.d/privoxy restart
			fi
		;;

		*off )
			sed -e 's/forward-socks4a/\# forward-socks4a/g' -i /etc/privoxy/config
			/etc/init.d/tor restart
			/etc/init.d/privoxy restart
		;;
	esac

}
