#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

# by gniourf_gniourf

sed -e "/$USER/d;s/:.*//g" /etc/group | \
	sed -e :a -e '/$/N;s/\n/ /;ta'
