#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2017 Christopher Bratusek		#
#							#
#########################################################

# by gniourf_gniourf

case ${1} in

	--help | -h)
		bsng-help -a "gniourf_gniourf" -e "" -h "http://www.commandlinefu.com/"\
				-l "Public Domain" -n "ngroups" -s "Show groups current user is not part of" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
				-o "none:|--"
	;;

	* )
		sed -e "/${USER}/d;s/:.*//g" /etc/group | \
			sed -e :a -e '/$/N;s/\n/ /;ta'
	;;

esac
