#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 ]]; then
	echo "octal $1 = binary $(oct2bin $1)"
	echo "octal $1 = decimal $(oct2dec $1)"
	echo "octal $1 = hexadecimal $(oct2hex $1)"
	echo "octal $1 = base32 $(oct2b32 $1)"
	echo "octal $1 = base64 $(oct2b64 $1)"
	echo "octal $1 = ascii $(oct2asc $1)"
fi
