#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bsng-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
				-l "GNU GPL v3" -n "oct2bin" -s "convert octal to binary" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
				-o "octal:|number to convert"
	;;

	* )
		echo "obase=2 ; ibase=8 ; $1" | bc
	;;

esac
