#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

# by iArno

case ${1} in

	--help | -h)
		bsng-help -a "iArno" -e "" -h "http://www.commandlinefu.com/"\
				-l "Public Domain" -n "ols" -s "ls -l with octal permissions" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
				-o "directory:|(optional) directory [or current]"
	;;

	* )
		ls -l "${1}" | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("%0o ",k);print}'
	;;

esac
