#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 ]]; then
	if [[ $2 ]]; then
		echo "$1 ^ $2" | bc
	else	echo "$1 ^ 2" | bc
	fi
fi
