#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2018 Christopher Bratusek		#
#							#
#########################################################

case ${1} in

	--help | -h | "")
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
				-l "GNU GPL v3" -n "radical" -s "Calculate square root of a number" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
				-o "number:|number to calculate square root of"
	;;

	* )
		echo "sqrt($1)" | bc -l
	;;

esac
