#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

random () {

	if [[ $1 == -l ]]; then
		echo $(cat /dev/urandom | tr -cd '[:digit:]' | head -c ${2-5})
	elif [[ $1 == -r ]]; then
		echo $((RANDOM%${2}))
	else	echo $((RANDOM%${1}))
	fi

}

randompw () {

	if [[ $2 == "!" ]]; then
		echo $(cat /dev/urandom | tr -cd '[:graph:]' | head -c ${1:-32})
	else	echo $(cat /dev/urandom | tr -cd '[:alnum:]' | head -c ${1:-32})
	fi
}

randomfile () {

	case $1 in

			-first)
				sed -n '1p' $HOME/.randomhistory
			;;

			-last)
				sed -n '$p' $HOME/.randomhistory
			;;

			-n)
				sed -n "${2}p" $HOME/.randomhistory
			;;

			-l)
				wc -l $HOME/.randomhistory | gawk '{print $1}'
			;;

			*)
				if [[ ! "$FILES" ]]; then
					files=(*)
				else	files=("$FILES")
				fi

				n=${#files[@]}

				RANDOMFILE="${files[RANDOM % n]}"

				echo "$RANDOMFILE" >> $HOME/.randomhistory

				if [[ ! "$1" ]]; then
					echo "$RANDOMFILE"
				else	"$1" "$RANDOMFILE"
				fi
			;;
	esac

}
