#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

if [[ $2 == "!" ]]; then
	echo $(cat /dev/urandom | tr -cd '[:graph:]' | head -c ${1:-32})
else	echo $(cat /dev/urandom | tr -cd '[:alnum:]' | head -c ${1:-32})
fi
