#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

# by xk2c (commandlinefu.com)

	--help | -h | "")
		bsng-help -a "xk2c" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
				-l "Public Domain" -n "reload" -s "convert any mencoder supported" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
				-o "none:|--"
	;;

	* )
		builtin unalias -a
		builtin unset -f $(builtin declare -F | sed 's/^.*declare[[:blank:]]\+-f[[:blank:]]\+//')
		source ~/.bashrc
	;;

esac
