#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

DEVICE=$1
shift
OPTS=$(mount | grep $DEVICE | sed -e 's/.*(//g' -e  's/)//g')

mount -oremount,$OPTS,$@ $DEVICE
