#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

if [[ $1 ]]; then
	if [[ $2 ]]; then
		echo "$(printf %.${2}f $1)"
	else	echo "$(printf %.0f $1)"
	fi
fi
