#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

show_tty_help ()
{

	echo -e "\n${ewhite}Usage:\n"
	echo -e "${eorange}show_tty${ewhite}|${egreen} ! no options !\n"
	tput sgr0

}

show_tty ()
{

	case $1 in
		*help )
			show_tty_help
		;;

		* )
			TTY=$(tty)
			echo ${TTY:5} | sed -e 's/\//\:/g'
		;;
	esac

}
