#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG 7.10				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

show_tty_help ()
{

	white=$(bs-ng-echo $white)
	orange=$(bs-ng-echo $orange)
	green=$(bs-ng-echo $green)

	echo -e "\n${white}Usage:\n"
	echo -e "${orange}show_tty${white}|${green} ! no options !\n"
	tput sgr0

}

show_tty ()
{

	case $1 in
		*help )
			show_tty_help
		;;

		* )
			TTY=$(tty)
			echo ${TTY:5} | sed -e 's/\//\:/g'
		;;
	esac

}
