#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

case $1 in
	*used )
		free -m | {
			read
			read desc total used free shared buffer available
			if [[ $used -lt 1000 ]]; then
				echo 0$used
			elif [[ $tused -lt 100 ]]; then
				echo 00$used
			else	echo $used
			fi
			}
	;;

	*free )
		free -m | {
			read
			read desc total used free shared buffer available
			temp=$((free+buffer))
			if [[ $temp -lt 1000 ]]; then
				echo 0$temp
			elif [[ $temp -lt 100 ]]; then
				echo 00$temp
			else	echo $temp
			fi
			}
	;;

	*total)
		free -m | {
			read
			read desc total used free shared buffer available
			if [[ $total -lt 1000 ]]; then
				echo 0$total
			elif [[ $total -lt 100 ]]; then
				echo 00$total
			else	echo $total
			fi
			}
	;;

	*used-percent )
		free | {
			read
			read desc total used free shared buffer available
			echo $((100*used/total))
			}
	;;

	*free-percent )
		free | {
			read
			read desc total used free shared buffer available
			temp=$((free+buffer))
			echo $((100*temp/total))
			}
	;;

	* )
		echo -e "\n${ewhite}Usage:\n"
		echo -e "\n${eorange}show_mem ${ewhite}|${egreen} --used ${eiceblue}[display used memory in mb (cache excluded)]\
		\n${eorange}show_mem ${ewhite}|${egreen} --free ${eiceblue}[display free memory in mb (cache excluded)]\
		\n${eorange}show_mem ${ewhite}|${egreen} --total ${eiceblue}[display total memory in mb]\
		\n${eorange}show_mem ${ewhite}|${egreen} --used-percent ${eiceblue}[display used memory in % (cache excluded)]\
		\n${eorange}show_mem ${ewhite}|${egreen} --free-percent ${eiceblue}[display free memory in % (cache excluded)]" | column -t
		echo ""
		tput sgr0
	;;
esac
