#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

case $1 in
	*used )
		temp=$(top -n1 | gawk '/Mem :/{print "(" $4 "-" $6 ") /1024"}' | bc)
		if [[ $temp -lt 1000 ]]; then
			echo 0$temp
		elif [[ $temp -lt 100 ]]; then
			echo 00$temp
		else	echo $temp
		fi
	;;

	*free )
		temp=$(top -n1 | gawk '/Mem :/{print $6 "/1024"}' | bc)
		if [[ $temp -lt 1000 ]]; then
			echo 0$temp
		elif [[ $temp -lt 100 ]]; then
			echo 00$temp
		else	echo $temp
		fi
	;;

	*total)
		temp=$(top -n1 | gawk '/Mem :/{print $4 "/1024"}' | bc)
		if [[ $total -lt 1000 ]]; then
			echo 0$total
		elif [[ $total -lt 100 ]]; then
			echo 00$total
		else	echo $total
		fi
	;;

	*used-percent )
		temp=$(top -n1 | gawk '/Mem :/{print "100*(" $4 "-" $6 ")/" $4}' | bc)
		echo "${temp}%"
	;;

	*free-percent )
		temp=$(top -n1 | gawk '/Mem :/{print "100 *" $6 "/" $4}' | bc)
		echo "${temp}%"
	;;

	* )
		echo -e "\n${ewhite}Usage:\n"
		echo -e "\n${eorange}show_mem ${ewhite}|${egreen} --used ${eiceblue}[display used memory in mb (cache excluded)]\
		\n${eorange}show_mem ${ewhite}|${egreen} --free ${eiceblue}[display free memory in mb (cache excluded)]\
		\n${eorange}show_mem ${ewhite}|${egreen} --total ${eiceblue}[display total memory in mb]\
		\n${eorange}show_mem ${ewhite}|${egreen} --used-percent ${eiceblue}[display used memory in % (cache excluded)]\
		\n${eorange}show_mem ${ewhite}|${egreen} --free-percent ${eiceblue}[display free memory in % (cache excluded)]" | column -t
		echo ""
		tput sgr0
	;;
esac
