#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

wget -qO - 'http://checkip.dyndns.org' | \
	sed 's/.*Current IP Address: \([0-9\.]*\).*/\1/g'
