#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

PROC=$1;COUNT=0
while [ -d /proc/$PROC ];do
	while [ "$COUNT" -lt 10 ];do
		echo -ne '\x08  ' ; sleep 0.1
		((COUNT++))
	done
	until [ "$COUNT" -eq 0 ];do
		echo -ne '\x08\x08 ' ; sleep 0.1
		((COUNT -= 1))
	done
done
