#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

echo -n "|/     |"
while [ -d /proc/$1 ]
do
	# moving right
	echo -ne "\b\b\b\b\b\b\b-     |"
	sleep .03
	echo -ne "\b\b\b\b\b\b\b\\     |"
	sleep .03
	echo -ne "\b\b\b\b\b\b\b|     |"
	sleep .03
	echo -ne "\b\b\b\b\b\b\b /    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b-    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b\\    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b|    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b /   |"
	sleep .03
	echo -ne "\b\b\b\b\b-   |"
	sleep .03
	echo -ne "\b\b\b\b\b\\   |"
	sleep .03
	echo -ne "\b\b\b\b\b|   |"
	sleep .03
	echo -ne "\b\b\b\b\b /  |"
	sleep .03
	echo -ne "\b\b\b\b-  |"
	sleep .03
	echo -ne "\b\b\b\b\\  |"
	sleep .03
	echo -ne "\b\b\b\b|  |"
	sleep .03
	echo -ne "\b\b\b\b / |"
	sleep .03
	echo -ne "\b\b\b- |"
	sleep .03
	echo -ne "\b\b\b\\ |"
	sleep .03
	echo -ne "\b\b\b| |"
	sleep .03
	echo -ne "\b\b\b /|"
	sleep .03
	echo -ne "\b\b-|"
	sleep .03
	echo -ne "\b\b\\|"
	sleep .03
	echo -ne "\b\b||"
	sleep .03
	echo -ne "\b\b/|"
	sleep .03

	# moving left
	echo -ne "\b\b||"
	sleep .03
	echo -ne "\b\b\\|"
	sleep .03
	echo -ne "\b\b-|"
	sleep .03
	echo -ne "\b\b\b/ |"
	sleep .03
	echo -ne "\b\b\b| |"
	sleep .03
	echo -ne "\b\b\b\\ |"
	sleep .03
	echo -ne "\b\b\b- |"
	sleep .03
	echo -ne "\b\b\b\b/  |"
	sleep .03
	echo -ne "\b\b\b\b|  |"
	sleep .03
	echo -ne "\b\b\b\b\\  |"
	sleep .03
	echo -ne "\b\b\b\b-  |"
	sleep .03
	echo -ne "\b\b\b\b\b/   |"
	sleep .03
	echo -ne "\b\b\b\b\b|   |"
	sleep .03
	echo -ne "\b\b\b\b\b\\   |"
	sleep .03
	echo -ne "\b\b\b\b\b-   |"
	sleep .03
	echo -ne "\b\b\b\b\b\b/    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b|    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b\\    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b-    |"
	sleep .03
	echo -ne "\b\b\b\b\b\b\b/     |"
	sleep .03
done
echo -e "\b\b\b\b\b\b\b\b\b|=======| done!"
