#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

BEGIN=$(date +%s)

while true; do
	NOW=$(date +%s)
	DIFF=$(($NOW - $BEGIN))
	MINS=$(($DIFF / 60))
	SECS=$(($DIFF % 60))
	echo -ne "Time elapsed: $MINS:`printf %02d $SECS`\r"
	sleep .1
done
