#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# This script is written by:                            #
#                               Dario Deho              #
#                                                       #
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

get_kde () {

	if [[ $SVN_USER_KDE ]]; then
		if [[ $1 == "-m" ]]; then
			svn co --user-name=$SVN_USER_KDE svn+ssh://svn.kde.org/home/kde/trunk/KDE/$2
		elif [[ $1 == "-mb" ]]; then
			svn co --user-name=$SVN_USER_KDE svn+ssh://svn.kde.org/home/kde/branches/KDE/$2
		fi
	fi

	if [[ $1 == "-b" ]]; then
		svn co svn://svn.kde.org/home/kde/branches/KDE/$2
	else	svn co svn://svn.kde.org/home/kde/trunk/KDE/$2
	fi

}

get_e () {

	if [[ $SVN_USER_ENLIGHTENMENT && $1 == "-m" ]]; then
		svn co svn+ssh://$SVN_USER_ENLIGHTENMENT@svn.enlightenment.org/var/svn/$2
	else
		svn co http://svn.enlightenment.org/svn/$2
	fi

}
