#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ -e $1 && -e $2 ]]; then
	mv "$1" temp.$$
	mv "$2" "$1"
	mv temp.$$ "$2"
fi
