#!/bin/bash
#########################################################
#                                                       #
# This is BashStyle-NG                                #
#                                                       #
# Licensed under GNU GENERAL PUBLIC LICENSE v3          #
#                                                       #
# Copyright 2007 - 2010 Christopher Bratusek            #
#                                                       #
#########################################################

system_infos_help()
{


	echo -e "\n${ewhite}Usage:\n"
	echo -e "${eorange}system_infos ${ewhite}|${egreen} --cpu\t\t${eiceblue} [Display CPU Model and Freq]\
	\n${eorange}system_infos ${ewhite}|${egreen} --kernel\t${eiceblue} [Display Kernel Version, Release and Machine]\
	\n${eorange}system_infos ${ewhite}|${egreen} --memory\t${eiceblue} [Display Total, Free and Used RAM]\
	\n${eorange}system_infos ${ewhite}|${egreen} --partitions\t${eiceblue} [Display Major, Minor, Blocks and Node for all Paritions]\
	\n${eorange}system_infos ${ewhite}|${egreen} --pci\t\t${eiceblue} [Display Infos about all PCI Devices (and their kernel-module)]\
	\n${eorange}system_infos ${ewhite}|${egreen} --usb\t\t${eiceblue} [Display Infos about all USB Devices (and their kernel-module)]\
	\n${eorange}system_infos ${ewhite}|${egreen} --bios\t${eiceblue} [Display SMBIOS DMI Infos]\
	\n${eorange}system_infos ${ewhite}|${egreen} --mounts\t${eiceblue} [Display all mounted devices]\n"
	tput sgr0
}

system_infos ()
{

	case $1 in
		*cpu)
			system_infos_cpu
		;;

		*kernel)
			system_infos_kernel
		;;

		*mem)
			system_infos_memory
		;;

		*partitions)
			system_infos_partitions
		;;

		*pci)
			check_opt lspci systeminfos::pci
			system_infos_pci
		;;

		*usb)
			check_opt lsusb systeminfos::usb
			system_infos_usb
		;;

		*mounts)
			system_infos_mounts
		;;

		*bios)
			check_opt dmidecode systeminfos::bios
			system_infos_bios
		;;

		*all)
			system_infos_cpu
			system_infos_kernel
			system_infos_memory
			system_infos_partitions
			#system_infos_pci
			#system_infos_usb
			system_infos_mounts
			#system_infos_bios
		;;

		*)
			system_infos_help
		;;
	esac

}

system_infos_cpu()
{
	echo -e "${ewhite}CPU:\n"
	echo -e "${eorange}Model:${eiceblue} $(grep "model name" /proc/cpuinfo | sed -e 's/.*: //g')"
	echo -e "${eorange}MHz  :${eiceblue} $(grep "cpu MHz" /proc/cpuinfo | sed -e 's/.*: //g')\n"
}

system_infos_kernel()
{
	echo -e "${ewhite}Kernel:\n"
	echo -e "${eorange}Release:${eiceblue} $(uname -r)"
	echo -e "${eorange}Version:${eiceblue} $(uname -v)"
	echo -e "${eorange}Machine:${eiceblue} $(uname -m)\n"

}

system_infos_memory()
{
	echo -e "${ewhite}RAM:\n"
	echo -e "${eorange}Total:${eiceblue} $(((`showmem --free`) + (`showmem --used`))) MB"
	echo -e "${eorange}Free :${eiceblue} $(showmem --free) MB"
	echo -e "${eorange}Used :${eiceblue} $(showmem --used) MB\n"

}

system_infos_partitions()
{
	echo -e "${ewhite}Partitions:${eorange}\n"
	echo -e "major minor blocks device-node ${eiceblue}\
	\n$(cat /proc/partitions | sed -e '1,2d')" | column -t
	echo ""

}

system_infos_pci()
{
	echo -e "${ewhite}PCI Devices:\n${eiceblue}"
	lspci -vkmm
	echo ""

}

system_infos_usb()
{
	echo -e "${ewhite}USB Devices:\n${eiceblue}"
	lsusb -v
	echo ""

}

system_infos_mounts()
{
	echo -e "${ewhite}Mounts:\n${eorange}\
	\ndevice-node on mount-point type filesystem options\n" ${eiceblue} "\n\n$(mount)" | column -t
	echo ""

}

system_infos_bios()
{
	if [[ $EUID != 0 ]]; then
		echo -e "How to auth as root? (sudo or su)\n"
		read auth

		if [[ $auth == sudo ]]; then
			echo -e "${ewhite}SMBIOS/DMI Infos:${eiceblue}\n"
			sudo dmidecode -q

		elif [[ $auth == su ]]; then
			echo -e "${ewhite}SMBIOS/DMI Infos:${eiceblue}\n"
			su -c "dmidecode -q"

		else	echo "wrong auth command"
		fi
	else	echo -e "${ewhite}SMBIOS/DMI Infos:${eiceblue}\n"
		dmidecode -q

	fi
}

