#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

history | awk '{print $2}' |\
awk 'BEGIN {FS="|"}{print $1}' |\
sort | uniq -c | sort -n | tail | sort -nr
