#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2017 Christopher Bratusek		#
#							#
#########################################################

case "${1}" in

	--help | -h | "")
		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "http://www.nanolx.org/"\
			-l "GNU GPL v3" -n "topdir" -s "determine deepest existing toplevel directory"\
			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
			-o "directory:/home/test/bin|path to test"
	;;

	* )
		dir="${1}"

		while [[ "$(dirname ${dir})" != "/" ]]; do
			dir=$(dirname "${dir}")
			if [[ -d "${dir}" ]]; then
				echo "${dir}"
				exit 0
			fi
		done

		exit 1
	;;
esac
