#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2013 Christopher Bratusek		#
#							#
#########################################################

ps f -u $USER -o command,pid,%cpu,%mem,time,etime,tty | \
	awk 'NR <= 1 {print;next} !/awk/ && $0~var' var=${1:-".*"}
