#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

if [[ $(alias | grep -w go-$1= ) != "" ]]; then
	sed -e "/go-$1/d" -i $HOME/.bookmarks
	xunalias go-$1
fi
