#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

if [[ $CD_WRITER ]]; then
	cdrecord dev=$CD_WRITER "$1"
else	cdrecord deV=/dev/dvdrw "$1"
fi
