#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

xchown () {

	user="$1"
	shift

	for df in "$@";
		do su -c "chown -R $user:$user \"$df\"";
	done

}
