#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG					#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

if [[ ${BASH_VERSINFO[0]} -ge "4" ]]; then

	shopt -s globstar

	[[ "$@" != "" ]] &&
		{ for argv in "$@"; do
			rm -fv ./**/*"$argv"
		done }

fi
