#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG 7.10				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

shopt -s globstar

xdel() {

	[[ $@ != "" ]] &&
		{ for argv in $@; do
			rm -fv ./**/*$argv
		done }

}
