#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG 7.10				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2009 Christopher Bratusek		#
#							#
#########################################################

xunalias() {

	for alias in $@; do
		[[ $(alias | grep -w $alias=) != "" ]] &&
			{ unalias $alias ; }
	done

}
