.TH "bashstyle" "1" 
.SH "NAME" 
bashstyle \(em Graphical user interface for managing Bash setup. 
.SH "SYNOPSIS" 
.PP 
\fBbashstyle\fR [\fIOPTIONS\fP]
.SH "DESCRIPTION" 
.PP 
BashStyle-NG is a graphical tool and toolchain for changing the behaviour and
look'n'feel of Bash, Readline, Vim, Nano and Git
.SH "OPTIONS" 
.IP "\fB\-h\fR, \fB\-\-help\fP" 10 
Display help message and copyright information
.IP "\fB-v\fR, \fB\-\-version\fP" 10 
Display version and exit
.IP "\fB\-p\fR, \fB\-\-prefix\fP" 10
Display prefix and exit
.IP "\fB-P\fR, \fB\-\-python\fP" 10
Display used python interpreter and exit
.SH "AUTHOR" 
.PP 
This manual page was written by Christopher Roy Bratusek nano@jpberlin.de
