.TH "bashstyle" "1" "(null)" "(null)" "(null)"
.SH "NAME"
bashstyle — Graphical user interface for managing Bash setup.
.br

.SH "SYNOPSIS"
\fBbashstyle \fR[\fIOPTIONS\fR]
.br

.SH "DESCRIPTION"
BashStyle-NG is a graphical tool and toolchain for changing the behaviour and look'n'feel of Bash, Readline, Vim, Nano and Git
.br

.SH "OPTIONS"
\fB-h\fR, \fB--help\fR
.br
          display help message and copyright information
.br

\fB-v\fR, \fB--version\fR
.br
          display version and exit
.br

\fB-p\fR, \fB--prefix\fR
.br
          display installation prefix and exit
.br

\fB-P\fR, \fB--python\fR
.br
          display used python interpreter; if additional args are given they will be passed to the used Python interpreter
.br

\fB-d\fR, \fB--doc\fR
.br
          open HTML documentation and exit
.br

\fB-u\fR, \fB--update\fR
.br
          update user configuration and exit
.br

\fB-b\fR, \fB--backup\fR
.br
          backup user configuration and exit
.br

\fB-r\fR, \fB--restore\fR
.br
          restore user configuration backup and exit
.br

\fB-R\fR, \fB--reset\fR
.br
          reset user configuration and exit
.br
