@c -*- texinfo -*-

@c To compile: makeinfo -I doc/ doc/userdoc.texi -o doc/bashstyle.info

@setfilename bashstyle.info
@settitle BashStyle-NG user documentation
@footnotestyle end

@ifnottex
@dircategory Miscellaneous
@direntry
* bashstyle: (bashstyle).       BashStyle-NG user documentation
@end direntry

This is the @cite{user documentation} for @b{BashStyle-NG}.

Copyright @copyright{} 2007 - 2026 Christopher Roy Bratušek.

@b{BashStyle-NG} is a graphical user interface for managing Bash and co.
@b{BashStyle-NG} runs on bash startup, if enabled, to manage all desired settings,
aswell as creating configuration files and providing additionial utilities.

@end ifnottex

@titlepage
@title bashstyle
@subtitle Graphical UI for managing Bash and co.
@subtitle User Documentation
@author Christopher Roy Bratušek.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2007 - 2026 Christopher Roy Bratušek.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.
@end titlepage

@node Top, Copying
@top BashStyle-NG Documentation

@menu
* Copying::                     Distribution conditions
* Introduction::                Brief introduction to BashStyle-NG
* Changelog::                   User readable list of version changes
* Installation::                Installation instructions
* First Start::                 First Start notes

* Style Options::               Options regarding colors and prompt style
* Prompt Styles::               Preview of all prompt styles
* Aliases::                     Options for setting shell aliases
* Advanced Options::            Advanced and non-default options for Bash
* Shell Options::               Shell options (shopt)
* Git Options::                 Options for the Git DVCS
* Readline Options::            Options for the Readline library
* Vim Options::                 Options for the Vi improved editor
* Nano Options::                Options for the GNU Nano editor
* LS Colors::                   Options for colorizing ls
* Manpage Colors::              Options for colorizing manpages
* GCC & Grep Colors::           Options for colorizing gcc and grep
* Key Bindings::                Key bindings setter for Bash/Readline
* Custom Prompt Builder::       UI for fully customized prompt experience

* Configuration Files::         Notes on various configuration files used

* Prompt Hooks::                Hooks for customizing predefinied prompt styles
* Utilities::                   Extra shell utilities provided by BashStyle-NG

* User Interface Icons::        Icon names for UI
@end menu

@node Copying, Introduction, Top, Top
@cindex Copying
@include userdoc_copying.texi

@node Introduction, Changelog, Copying, Top
@cindex Introduction
@include userdoc_introduction.texi

@node Changelog, Installation, Introduction, Top
@cindex Changelog
@include news.texi

@node Installation, First Start, Changelog, Top
@cindex Installation
@include userdoc_install.texi

@node First Start, Style Options, Installation, Top
@cindex First Start
@include userdoc_firststart.texi

@node Style Options, Prompt Styles, First Start, Top
@cindex Style Options
@include userdoc_style.texi

@node Prompt Styles, Aliases, Style Options, Top
@cindex Prompt Styles
@include userdoc_prompts.texi

@node Aliases, Advanced Options, Prompt Styles, Top
@cindex Aliases
@include userdoc_aliases.texi

@node Advanced Options, Shell Options, Aliases, Top
@cindex Advanced Options
@include userdoc_advanced.texi

@node Shell Options, Git Options, Advanced Options, Top
@cindex Shell Options
@include userdoc_shopts.texi

@node Git Options, Readline Options, Shell Options, Top
@cindex Git Options
@include userdoc_git.texi

@node Readline Options, Vim Options, Git Options, Top
@cindex Readline Options
@include userdoc_readline.texi

@node Vim Options, Nano Options, Readline Options, Top
@cindex Vim Options
@include userdoc_vim.texi

@node Nano Options, LS Colors, Vim Options, Top
@cindex Nano Options
@include userdoc_nano.texi

@node LS Colors, Manpage Colors, Nano Options, Top
@cindex LS Colors
@include userdoc_lscolors.texi

@node Manpage Colors, GCC & Grep Colors, LS Colors, Top
@cindex Manpage Colors
@include userdoc_manpage.texi

@node GCC & Grep Colors, Key Bindings, Manpage Colors, Top
@cindex GCC & Grep Colors
@include userdoc_gcc_grep.texi

@node Key Bindings, Custom Prompt Builder, Manpage Colors, Top
@cindex Key Bindings
@include userdoc_keybindings.texi

@node Custom Prompt Builder, Configuration Files, Key Bindings, Top
@cindex Custom Prompt Builder
@include userdoc_cpb.texi

@node Configuration Files, Prompt Hooks, Custom Prompt Builder, Top
@cindex Configuration Files
@include userdoc_configurationfiles.texi

@node Prompt Hooks, Utilities, Configuration Files, Top
@cindex Prompt Hooks
@include userdoc_prompthooks.texi

@node Utilities, User Interface Icons, Prompt Hooks, Top
@cindex Utilities
@include userdoc_utils.texi

@node User Interface Icons, , Utilities, Top
@cindex User Interface Icons
@include userdoc_iconnames.texi
