#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

bashstyle-remember-command-error () {
	local _lastexit=$?
	[[ "${BSNG_TRAP_RECORD}" == True ]] && return
	lastexit=${_lastexit}
}
