#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

bashstyle-reload-bash () {
	#xk2c from commandlinefu.com
	builtin unalias -a
	builtin unset -f "$(builtin compgen -A function)"
	[ -f /etc/bash_completion ] && source /etc/bash_completion
	source "${HOME}"/.bashrc
}
