#!/bin/bash
#########################################################
#                                                       #
# This is BashStyle-NG                                	#
#                                                       #
# Licensed under GNU GENERAL PUBLIC LICENSE v3          #
#                                                       #
# Copyright 2007 - 2019 Christopher Bratusek            #
#                                                       #
#########################################################

dbg_msg "$(eval_gettext "BashStyle-NG Setting:")" LS_COLORS

lblack="${style};30"
lred="${style};31"
lgreen="${style};32"
lyellow="${style};33"
lblue="${style};34"
lmagenta="${style};35"
lcyan="${style};36"
lgrey="${style};37"
lwhite="${style};38"

if [[ ${TERM} != *xterm*color* ]]; then
	lcoldblue=${lblue}
	lsmoothblue=${lblue}
	liceblue=${lblue}
	lturqoise=${lcyan}
	lsmoothgreen=${lgreen}
	lwinered=${lred}
	lbrown=${lyellow}
	lsilver=${lwhite}
	locher=${lyellow}
	lorange=${lyellow}
	lpurple=${lmagenta}
	lpink=${lmagenta}
	lcream=${lmagenta}
else
	ecoldblue="${style};38;5;33m"
	esmoothgreen="${style};38;5;42m"
	eiceblue="${style};38;5;45m"
	eturqoise="${style};38;5;50m"
	epurple="${style};38;5;92m"
	esmoothblue="${style};38;5;111m"
	ewinered="${style};38;5;125m"
	ebrown="${style};38;5;130"
	eocher="${style};38;5;136m"
	epink="${style};38;5;200m"
	ecream="${style};38;5;218m"
	eorange="${style};38;5;202m"
	esilver="${style};38;5;245m"
fi

if bt $(ini_get dark_terminal); then
	lblack=${lwhite}
else	lwhite=${lblack}
fi

lscolors=(exec generic logs deb rpm dirs jpeg png gif mp3 ogg flac tar targz
tarbz2 tarxz zip rar link socket pipe blockdev chardev)

for lscolor in "${lscolors[@]}"; do
	eval "_${lscolor}"=$(ini_get "${lscolor}")
done

_custom="$(ini_get custom)"

dbg_log export LS_COLORS="*=${_generic}:ex=${_exec}:*.log=${_logs}:*.deb=${_deb}:\
*.rpm=${_rpm}:di=${_dirs}:*.jpg=${_jpeg}:*.jpeg=${_jpeg}:*.png=${_png}:*.gif=${_gif}:\
*.mp3=${_mp3}:*.ogg=${_ogg}:*.flac=${_flac}:*.tar=${_tar}:*.tar.gz=${_targz}:\
*.tgz=${_targz}:*.tar.bz2=${_tarbz2}:*.tbz=${_tarbz2}:*.tar.xz=${_tarxz}:\
*.zip=${_zip}:*.rar=${_rar}:ln=${_link}:so=${_socket}:pi=${_pipe}:bd=${_blockdev}:\
cd=${_chardev}:${_custom}"

dbg_msg "$(eval_gettext "LS_COLORS Setting:")" LS_COLORS "${LS_COLORS}"

for lscolor in "${lscolors[@]}"; do
	eval unset "_${lscolor}"
done

unset _custom color_style style lscolor lscolors
