#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

shopt -s nullglob
bsng_nanorc=( "${HOME}"/.nanorc.bs-ng.* )
shopt -u nullglob

if (( "${#bsng_nanorc[@]}" == 0 )); then

	dbg_msg $"BashStyle-NG Loading:" NanoCFG
	export RC_FILE
	RC_FILE="${HOME}/.nanorc.bs-ng.${BSNG_SESSION_TIME}"

	if bt $(ini_get auto_indent); then
		dbg_msg $"NanoCFG Setting:" Auto-Indention $"On"
		rc_add "set autoindent"
	else
		dbg_msg $"NanoCFG Setting:" Auto-Indention $"Off"
		rc_add "unset autoindent"
	fi

	if bt $(ini_get nano_backup); then
		dbg_msg $"NanoCFG Setting:" Autosave $"On"
		rc_add "set backup"
	else
		dbg_msg $"NanoCFG Setting:" Autosave $"Off"
		rc_add "unset backup"
	fi

	if bt $(ini_get bold_text); then
		dbg_msg $"NanoCFG Setting:" Bold-Text $"On"
		rc_add "set boldtext"
	else
		dbg_msg $"NanoCFG Setting:" Bold-Text $"Off"
		rc_add "unset boldtext"
	fi

	if bt $(ini_get case_sensitive); then
		dbg_msg $"NanoCFG Setting:" Case-Sensitive $"On"
		rc_add "set casesensitive"
	else
		dbg_msg $"NanoCFG Setting:" Case-Sensitive $"Off"
		rc_add "unset casesensitive"
	fi

	if bt $(ini_get show_positon); then
		dbg_msg $"NanoCFG Setting:" Show-Position $"On"
		rc_add "set constantshow"
	else
		dbg_msg $"NanoCFG Setting:" Show-Position $"Off"
		rc_add "unset constantshow"
	fi

	if bt $(ini_get empty_space); then
		dbg_msg $"NanoCFG Setting:" More-Space $"On"
		rc_add "unset emptyline"
	else
		dbg_msg $"NanoCFG Setting:" More-Space $"Off"
		rc_add "set emptylines"
	fi

	if bt $(ini_get hide_help); then
		dbg_msg $"NanoCFG Setting:" No-Help $"On"
		rc_add "set nohelp"
	else
		dbg_msg $"NanoCFG Setting:" No-Help $"Off"
		rc_add "unset nohelp"
	fi

	if bt $(ini_get history); then
		dbg_msg $"NanoCFG Setting:" History Log: $"On"
		rc_add "set historylog"
	else
		dbg_msg $"NanoCFG Setting:" History Log: $"Off"
		rc_add "unset historylog"
	fi

	if bt $(ini_get rebind_delete); then
		dbg_msg $"NanoCFG Setting:" Rebind Delete: $"On"
		rc_add "set rebinddelete"
	else
		dbg_msg $"NanoCFG Setting:" Rebind Delete: $"Off"
		rc_add "unset rebinddelete"
	fi

	if bt $(ini_get enable_mouse); then
		dbg_msg $"NanoCFG Setting:" Enable Mouse: $"On"
		rc_add "set mouse"
	else
		dbg_msg $"NanoCFG Setting:" Enable Mouse: $"Off"
		rc_add "unset mouse"
	fi

	if bt $(ini_get no_wrap); then
		dbg_msg $"NanoCFG Setting:" No Wrap $"On"
		rc_add "set nowrap"
	else
		dbg_msg $"NanoCFG Setting:" No Wrap $"Off"
		rc_add "unset nowrap"
	fi

	if bt $(ini_get log_position); then
		dbg_msg $"NanoCFG Setting:" Log Position $"On"
		rc_add "set positionlog"
	else
		dbg_msg $"NanoCFG Setting:" Log Position $"Off"
		rc_add "unset positionlog"
	fi

	dbg_msg $"NanoCFG Setting:" Tab Width "$(ini_get tab_size)"
	rc_add "set tabsize $(ini_get tab_size)"

	if bt $(ini_get tab_to_spaces); then
		dbg_msg $"NanoCFG Setting:" Tab to spaces $"On"
		rc_add "set tabstospaces"
	else
		dbg_msg $"NanoCFG Setting:" Tab to spaces $"Off"
		rc_add "unset tabstospaces"
	fi

	if bt $(ini_get line_number); then
		dbg_msg $"NanoCFG Setting:" Line Numbers $"On"
		rc_add "set linenumbers"
	else
		dbg_msg $"NanoCFG Setting:" Line Numbers $"Off"
		rc_add "unset linenumbers"
	fi

	if [ $(ini_get guide_stripe) -gt 0 ]; then
		dbg_msg $"NanoCFG Setting:" Guide Stripe "$(ini_get guide_stripe)"
		rc_add "set tabsize $(ini_get tab_size)"
	else
		dbg_msg $"NanoCFG Setting:" Guide Stripe $"Off"
	fi

	if bt $(ini_get set_uicolors); then
		for uipart in function key status title number error selected stripe number; do
			uipart_color="$(ini_get ${uipart}_color_fg),$(ini_get ${uipart}_color_bg)"
			dbg_msg $"NanoCFG Setting:" UI Color "${uipart}": "${uipart_color}"
			rc_add "set ${uipart}color ${uipart_color}"
		done

		unset uipart_color
	fi

	if bt $(ini_get syntax_highlight); then
		dbg_msg $"NanoCFG Setting:" Colors $"On"
		for file in /usr/share/nano/*.nanorc; \
			do rc_add "include \"$file\""; \
		done
	else	dbg_msg $"NanoCFG Setting:" Colors $"Off"
	fi

	mv "${RC_FILE}" "${HOME}"/.nanorc
	unset RC_FILE

fi

rm -f "${HOME}"/.nanorc.bs-ng.${BSNG_SESSION_TIME}
