#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2020 Christopher Bratusek		#
#							#
#########################################################

sepa=$(ini_get separator)

PS1="\n${color_user}\u${color_font} @${color_host} \h${color_separator} ${sepa} ${color_date}\d${color_separator} ${sepa} ${color_time}\t${color_separator} ${sepa} ${color_wdir}\$(truncpwd)"
[[ $(ini_get files_amount) == True ]] && PS1="${PS1} files: \$(systemkit countvisiblefiles)"
[[ $(ini_get files_amount) == True && $(ini_get file_size) == True ]] && PS1="${PS1}${color_separator} /"
[[ $(ini_get file_size) == True ]] && PS1="${PS1}${color_wdir} size: \$(systemkit dirsize)"
[[ $(ini_get tty) == True ]] && PS1="${PS1} ${color_separator}${sepa}${color_host} tty: \$(systemkit tty)"
[[ $(ini_get uptimes) == True ]] && PS1="${PS1} ${color_separator}${sepa}${color_uptime} uptime: \$(systemkit uptime)"
[[ $(ini_get load) == True ]] && PS1="${PS1} ${color_separator}${sepa}${color_uptime} system load: \$(systemkit load1)"
[[ $(ini_get processes) == True ]] && PS1="${PS1} ${color_separator}${sepa}${color_ps} processes: \$(systemkit processes)"
[[ $(ini_get battery_load) == True ]] && PS1="${PS1} ${color_separator}${sepa}${color_ps} battery: \$(systemkit battery)"
[[ $(ini_get mem) == free ]] && PS1="${PS1} ${color_separator}${sepa}${color_user} free mem: ${color_ps}\$(systemkit freeram)${color_user} mb"
[[ $(ini_get mem) == used ]] && PS1="${PS1} ${color_separator}${sepa}${color_user} used mem: ${color_ps}\$(systemkit usedram)${color_user} mb"
[[ $(ini_get mem) == both ]] && PS1="${PS1} ${color_separator}${sepa}${color_user} free${color_separator}/${color_user}used mem: ${color_ps}\$(systemkit freeram)${color_separator}/${color_ps}\$(systemkit usedram)${color_user} mb"
PS1="${PS1}${color_separator} ${sepa}\n${SEPA_1_COLOR}\$(SEPA_1)${color_user}\$(showuser) $SEPA_2_COLOR\$(SEPA_2)${color_font}-> "

unset sepa
