#!/bin/bash
#########################################################
#                                                       #
# This is BashStyle-NG                                  #
#                                                       #
# Licensed under GNU GENERAL PUBLIC LICENSE v3          #
#                                                       #
# Copyright Christopher Roy Bratušek                    #
#                                                       #
#########################################################

_show_editmode=$(ini_get show_editmode)
check bt ${_show_editmode} && _prompt_prefix=' '

PS1="\n${color_ps}${_prompt_prefix}.:${color_separator}[ ${color_user}\u${color_ps} @ ${color_host}\h${color_separator} ]${color_ps}:. \
.:${color_separator}[ ${color_wdir}\$(truncpwd)${color_separator} ]${color_ps}:.\n\
.:${color_separator}[·>${color_font} "

unset _show_editmode