#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright Christopher Bratusek			#
#							#
#########################################################

PS1="\n${color_separator}⊏⁅ ${color_user}\u${color_ps} ⁑ ${color_host}\h ${color_separator}⁆⁅ ${color_date}\d ${color_ps}⁑ ${color_time}\t${color_ps} ⁑ ${color_uptime}\$(systemkit uptime)${color_separator} ⁆⊐
⊏⁅${color_wdir} \$(truncpwd)${SEPA_NG_1_COLOR}\$(SEPA_NG_1) ${color_separator}⁆⊐≻${color_font} "
