#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

APP_NAME="BashStyle-NG"
APP_VERSION=10.6.90
APP_CODENAME="Kaffee Filtrino"
APP_LANGUAGES="de"

CFG_VERSION="4.4.5"

if [[ -d "/usr/lib/girepository-1.0/" ]]; then
	export GIRPATH="/usr/lib/girepository-1.0"
elif [[ -d "/usr/lib64/girepository-1.0/" ]]; then
	export GIRPATH="/usr/lib64/girepository-1.0"
else
	missing_girpath_message
fi

PREFIX="/usr"
PYTHON=$(which python3 || which python2 || which python)

BINDIR="${PREFIX}/bin"
PCDIR="${PREFIX}/share/pkgconfig"
DATADIR="${PREFIX}/share"
DOCDIR="${DATADIR}/doc"
MANDIR="${DATADIR}/man"

PYMINVER_P="2.7.0"
PYMAXVER_P="3.9.0"

PYMINVER=${PYMINVER_P//.}
PYMAXVER=${PYMAXVER_P//.}

DISABLE_POSTINSTALL=0

for lang in "${APP_LANGUAGES[@]}"; do
	LC_MESSAGES_DIRS+="${lang}/LC_MESSAGES"
done

export OLDPATH=${PATH}
export PATH="${PATH}:/sbin:/usr/sbin:/usr/local/sbin"

export_result ()
{
	echo -e "PREFIX=\"${PREFIX}\"
DATADIR=\"${DATADIR}/bashstyle-ng\"
DATADIR_LIST=(functions ui rc)
DOCDIR=\"${DOCDIR}/bashstyle-ng\"
MANDIR=\"${MANDIR}/man1\"
BINDIR=\"${BINDIR}\"
LOCALEDIR=\"${DATADIR}/locale\"
LOCALEDIR_LIST=(${LC_MESSAGES_DIRS})
ICONDIR=\"${DATADIR}/icons/hicolor/32x32/apps\"
DESKTOPDIR=\"${DATADIR}/applications\"
PCDIR=\"${PCDIR}\"
APP_LANGUAGES=\"${APP_LANGUAGES}\"
DISABLE_POSTINSTALL=${DISABLE_POSTINSTALL}" \
	> "${PWD}"/.configure/results
}
