#!/bin/bash

export xVERSION=7.12
CODENAME="Planetary Collapse"

ERR_MSG=""

export OLDPATH=$PATH
export PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"

export_result ()
{

	RES=$PWD/.configure/results

	if [[ -e $RES ]]; then
		rm $RES
	fi

	echo MODE=\"$MODE\" >> $RES
	echo PREFIX=\"$PREFIX\" >> $RES
	echo DATADIR=\"$PREFIX/share/bashstyle-ng/\" >> $RES
	echo DATADIR_LIST=\"\( code data rc/{,ascii,bin,dirinfo,functions,internal,settings,styles,wizard} \
		terminfo/{,b,m,n} vim/{,colors} \)\" >> $RES
	echo PROFILEDIR=\"/etc/profile.d/\" >> $RES
	echo BINDIR=\"$PREFIX/bin\" >> $RES
	echo LOCALEDIR=\"$PREFIX/share/locale/\" >> $RES
	echo LOCALEDIR_LIST=\"\( {de,es,it,ru}/LC_MESSAGES/ \)\" >> $RES
	echo ICONDIR=\"/usr/icons/hicolor/32x32/apps/\" >> $RES
	echo DOCDIR=\"$PREFIX/share/doc/bashstyle-ng/\" >> $RES
	echo DOCDIR_LIST=\"\( img img-style \)\" >> $RES
	echo DIRINFO_ENABLE=\"$DIRINFO_ENABLE\" >> $RES
	echo MISSING=\"\( $MISSING \)\" >> $RES

}
