#!/bin/bash

export xVERSION=8.1
CODENAME="Sonic Empire"

ERR_MSG=""

if [[ -d "/usr/lib/girepository-1.0/" ]]; then
	export GIRPATH="/usr/lib/girepository-1.0/"
elif [[ -d "/usr/lib64/girepository-1.0/" ]]; then
	export GIRPATH="/usr/lib64/girepository-1.0/"
fi

PREFIX="/usr"
DIRINFO_ENABLE="false"
MODE=user
QUIET=false
PYTHON=$(which python)

BINDIR="$PREFIX/bin"
PCDIR="$PREFIX/lib/pkgconfig/"
DATADIR="$PREFIX/share/"
DOCDIR="$DATADIR/doc/"
PROFILEDIR="/etc/profile.d/"

export OLDPATH=$PATH
export PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"

export_result ()
{

	if [[ -e $PWD/.configure/results ]]; then
		rm $PWD/.configure/results
	fi

	echo -e "MODE=\"$MODE\"\
\nPREFIX=\"$PREFIX\"\
\nDATADIR=\"$DATADIR/bashstyle-ng/\"\
\nDATADIR_LIST=( bin ui data rc/{,ascii,dirinfo,functions,generator,internal,settings,styles,wizard} terminfo/{,b,m,n} vim/{,colors} )\
\nPROFILEDIR=\"$PROFILEDIR/\"\
\nBINDIR=\"$BINDIR\"\
\nLOCALEDIR=\"$DATADIR/locale/\"\
\nLOCALEDIR_LIST=( {de,es,it,ru}/LC_MESSAGES/ )\
\nICONDIR=\"$DATADIR/icons/hicolor/32x32/apps/\"\
\nDOCDIR=\"$DOCDIR/bashstyle-ng/\"\
\nDOCDIR_LIST=( img img-style )\
\nPCDIR=\"$PCDIR/\"\
\nDIRINFO_ENABLE=\"$DIRINFO_ENABLE\"\
\nMISSING=($MISSING )" | sed -e 's,\/\/,\/,g' >> $PWD/.configure/results

}
