#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2018 Christopher Bratusek		#
#							#
#########################################################

RED="\033[01;31m"
GREEN="\033[01;32m"
YELLOW="\033[01;33m"
BLUE="\033[01;34m"
MAGENTA="\033[01;35m"
CYAN="\033[01;36m"
WHITE="\033[01;37m"

if [[ ${TERM} != *xterm* ]]; then
	SMOOTHBLUE=${BLUE}
	ORANGE=${YELLOW}
	CREAM=${MAGENTA}
	SILVER=${WHITE}
else
	SMOOTHBLUE="\033[01;38;5;111m"
	ORANGE="\033[01;38;5;714m"
	CREAM="\033[01;38;5;5344m"
	SILVER="\033[01;38;5;761m"
fi
