#!/bin/bash

display_help () {

	echo -e "\n${GREEN}BashStyle-NG ${YELLOW}(configure) ${CYAN}help"
	echo -e "\n${WHITE}Options:\n"
	echo -e "\n${ORANGE}--help${WHITE} |${GREEN} Display this help message\
	\n${ORANGE}--mm${WHITE} |${GREEN} Enter Maintainer Mode (disable checks)\
	\n${ORANGE}--prefix=${WHITE} |${GREEN} Change Installation Prefix (default /usr)" | column -t
	echo ""
	tput sgr0

}
