#!/bin/bash

IN_FILES=( rc/nx-rc data/bashstyle data/bashstyle-ng.pc data/bashstyle.sh )

copy_in_files () {

	for in_file in ${IN_FILES[@]}; do
		cp "${in_file}".in "${in_file}";
	done

}

substitute_values () {

	sed -e "s>@VERSION@>$xVERSION>g" \
		-e "s>@PREFIX@>$PREFIX>g" \
		-e "s>@DATADIR@>$DATADIR>g" \
		-e "s>@DIRINFO_ENABLE@>$DIRINFO_ENABLE>g" \
		-e "s>@DOCDIR@>$DOCDIR>g" \
		-e "s>@PYTHON@>$PYTHON>g" \
		-e "s>@PROFILEDIR@>$PROFILEDIR>g" -i ${IN_FILES[@]}
	sed -e "s>//>/>g" -i ${IN_FILES[@]}

}
