#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

local _lastexit=$?
[[ "${BSNG_TRAP_RECORD}" != True ]] && return
[ -n "$COMP_LINE" ] && return
[ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && return
[[ "$BASH_COMMAND" == trap\ * ]] && return
[[ "$BASH_COMMAND" == *lastcommand* ]] && return
[[ "$BASH_COMMAND" == *lastexit* ]] && return

local X_COMMAND=${BASH_COMMAND//$'\n'/ }
X_COMMAND=${X_COMMAND//\\n/ }

lastcommand=${BASH_COMMAND}
lastcommandprintable=${X_COMMAND:0:21}

if [ ${#lastcommandprintable} -gt 21 ]; then
	lastcommandprintable=${lastcommandprintable:0:20}'>'
else
	lastcommandprintable="$(printf '%-21s' "$lastcommandprintable")"
fi

lastexit=${_lastexit}
