#!/bin/bash
#########################################################
#                           #
# This is BashStyle-NG                  #
#                           #
# Licensed under GNU GENERAL PUBLIC LICENSE v3      #
#                           #
# Copyright Christopher Roy Bratušek            #
#                           #
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

case ${1} in
    --help | -h | "")
        bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
            -l "GNU GPL v3" -n "list" -s "$(eval_gettext "various ls variants")"\
            -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
            -o "$(eval_gettext "single:|one-column ls, directories first")"\
            -o "$(eval_gettext "group:|show group for files in directory")"\
            -o "$(eval_gettext "verbose:|detailed ls without hidden files")"\
            -o "$(eval_gettext "detailed:|detailed ls including hidden files")"\
            -o "$(eval_gettext "voctal:|detailed ls without hidden files (octal perms)")"\
            -o "$(eval_gettext "doctal:|detailed ls including hidden files (octal perms)")"\
            -o "$(eval_gettext "perm:|show plain and octal permissions for files")"\
            -o "$(eval_gettext "owner:|show owner for files in directory")"
    ;;

    -s | single)
        ls -1 --group-directories-first "${@:2}"
    ;;
    -g | group )
        stat -c "%n in Group -> %G" "${@:2}" 2>/dev/null | column -t
    ;;
    -v | verbose)
        ls -l --group-directories-first "${@:2}"
    ;;
    -d | detailed)
        ls -Al --group-directories-first "${@:2}"
    ;;
    -p | perm)
        find "${@:2}" -maxdepth 1 -printf "Permissions of %f -> %M (%m)\n" 2>/dev/null | column -t
    ;;
    -o | owner)
        stat -c "%n by User -> %U" "${@:2}" 2>/dev/null | column -t
    ;;
    -V | voctal)
        stat -c "%a %A %F %U %G %s %y %n" "${@:2}" 2>/dev/null
    ;;
    -D | doctal)
        find "${@:2}" -maxdepth 1 -mindepth 1 -exec stat -c "%a %A %F %U %G %s %y %n" {} + 2>/dev/null
    ;;
esac
