#!/bin/bash
#########################################################
#                                                       #
# This is BashStyle-NG                                  #
#                                                       #
# Licensed under GNU GENERAL PUBLIC LICENSE v3          #
#                                                       #
# Copyright Christopher Roy Bratušek                    #
#                                                       #
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

case ${1} in
    --help | -h)
        bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org"\
            -l "GNU GPL v3" -n "ruler" -s "$(eval_gettext "print a numbered ruler on the terminal")"\
            -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
            -o "$(eval_gettext "none:|--")"
    ;;

    * )
        cols=$(tput cols)

        while [ ${#line1} -lt "$cols" ]; do
            line1+="....^....|"
            line2+="123456789|"
        done

        printf "%.${cols}s\n" "$line1"
        printf "%.${cols}s\n" "$line2"
    ;;
esac

