#!/bin/bash
#########################################################
#                                                       #
# This is BashStyle-NG                                  #
#                                                       #
# Licensed under GNU GENERAL PUBLIC LICENSE v3          #
#                                                       #
# Copyright Christopher Roy Bratušek                    #
#                                                       #
#########################################################

. gettext.sh
export TEXTDOMAIN="bashstyle-rc"

case ${1} in
    -h | --help )
        bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
            -l "GNU GPL v3" -n "stopwatch" -s "$(eval_gettext "a simple stopwatch")"\
            -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
            -o "$(eval_gettext "none:|--")"
    ;;

    *)
        SECONDS=0

        while true; do
            printf "\r$(eval_gettext "Time elapsed:") %d:%02d" $((SECONDS / 60)) $((SECONDS % 60))
            sleep 1
        done
    ;;
esac
