#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

make_news () {
	makeinfo --no-validate  --no-headers doc/news.texi > NEWS
}

make_info () {
	makeinfo -I ${PWD}/doc/ doc/userdoc.texi -o doc/bashstyle.info
}

make_info_html () {
	makeinfo -I ${PWD}/doc/ --html doc/userdoc.texi -o doc/html
}

make_build () {
	check_configure && 
	build_message && 
	generate_mo &&
	touch ${PWD}/.make/build_done
}

make_install () {
	check_configure &&
	check_built &&
	check_root "install" &&
	install_message && 
	installdirs_create &&
	install_bsng && 
	post_install
}

make_remove () {
	check_configure &&
	check_root "remove" &&
	remove_message && 
	remove_bsng &&
	post_remove
}

CLEAN_FILES=( data/bashstyle data/bashstyle-ng.pc ui/bashstyle.ui.h
		data/bashstyle.sh rc/nx-rc i18n/??/*.mo i18n/*.pot
		.configure/results .make/build_done ui/#bashstyle.ui#
		ui/bashstyle.ui~ doc/bashstyle.info )

CLEAN_DIRS=( doc/html )

make_clean () {
	clean_message
	for file in ${CLEAN_FILES[@]}; do
		rm -f "${file}"
	done

	for dir in ${CLEAN_DIRS[@]}; do
		rm -rf "${dir}"
	done
}
