#!/bin/bash

update_cache () {

	gtk-update-icon-cache -f $PREFIX/share/icons/hicolor 2>/dev/null

}

remove_old_wrappers () {

	rm -rf $DESTDIR/$PREFIX/share/bashstyle-ng/rc/bin/
}

post_install () {

	if [[ ! $DISABLE_POSTINSTALL ]]; then

		echo -e "\t${WHITE}+ ${WHITE} post-installation tasks"
		update_cache
		remove_old_wrappers

	fi

}
