#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2019 Christopher Bratusek		#
#							#
#########################################################

check_configure () {
	if [[ ! -f "${PWD}/.configure_results" ]]; then
		run_configure_message
		exit 1
	else	source "${PWD}/.configure_results"
		source "${PWD}/.make/files"
	fi
}

check_built () {
	if [[ ! -f "${PWD}/.make/build_done" ]]; then
		run_make_build_message
		exit 1
	fi
}

check_root () {
	if [[ ${EUID} -ne 0 ]]; then
		check_root_message "${1}"
		exit 1
	fi
}
