#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
#							#
#########################################################

DATA_FILES=( ui/*.{py,ui}:${DATADIR}/ui
	     rc/nx-rc:${DATADIR}/rc
	     rc/ascii/*:${DATADIR}/rc/ascii
	     rc/dirinfo/*:${DATADIR}/rc/dirinfo
	     rc/internal/*:${DATADIR}/rc/internal
	     rc/settings/*:${DATADIR}/rc/settings
	     rc/styles/*:${DATADIR}/rc/styles
	     data/termcap/bar/*:${DATADIR}/termcap/bar
	     data/termcap/body/*:${DATADIR}/termcap/body
	     data/vim/colors/*:${DATADIR}/vim/colors
	     data/CharName.pm:${DATADIR}
	     data/*.ini:${DATADIR} )

LOCALE_FILES=( i18n/de/*.mo:${LOCALEDIR}/de/LC_MESSAGES
	       i18n/es/*.mo:${LOCALEDIR}/es/LC_MESSAGES
	       i18n/it/*.mo:${LOCALEDIR}/it/LC_MESSAGES
	       i18n/ru/*.mo:${LOCALEDIR}/ru/LC_MESSAGES )

BIN_FILES=( data/bashstyle:${BINDIR}
	    bin-extra/*:${DATADIR}/bin
	    rc/functions/*:${DATADIR}/rc/functions )

PROFILE_FILES=( data/bashstyle.sh:${PROFILEDIR} )

ICON_FILES=( data/icons/*.png:${ICONDIR} )

PC_FILES=( data/bashstyle-ng.pc:${PCDIR} )

REMOVE_FILES=( ${LOCALEDIR}/{de,es,it,ru}/{bs-ng,nx-rc}.mo
	       ${BINDIR}/bashstyle
	       ${ICONDIR}/bs-ng*.png
	       ${PCDIR}/bashstyle-ng.pc
	       ${PROFILEDIR}/bashstyle.sh
	       ${DATADIR} )
