#!/bin/bash

DATA_FILES=( ui/bsng.py:${DATADIR}/ui
	     ui/undobuffer.py:${DATADIR}/ui
	     ui/bashstyle7.ui:${DATADIR}/ui
	     rc/nx-rc:${DATADIR}/rc
	     rc/ascii/*:${DATADIR}/rc/ascii
	     rc/dirinfo/*:${DATADIR}/rc/dirinfo
	     rc/functions/*:${DATADIR}/rc/functions
	     rc/internal/*:${DATADIR}/rc/internal
	     rc/settings/*:${DATADIR}/rc/settings
	     rc/styles/*:${DATADIR}/rc/styles
	     rc/wizard/*:${DATADIR}/rc/wizard
	     rc/generator/*:${DATADIR}/rc/generator
	     data/terminfo/b/*:${DATADIR}/terminfo/b
	     data/terminfo/m/*:${DATADIR}/terminfo/m
	     data/terminfo/n/*:${DATADIR}/terminfo/n
	     data/vim/colors/*:${DATADIR}/vim/colors )

LOCALE_FILES=( translations/mo/bs-ng-de.mo:${LOCALEDIR}/de/LC_MESSAGES/bashstyle-ng.mo
               translations/mo/nx-rc-de.mo:${LOCALEDIR}/de/LC_MESSAGES/nx-rc.mo
	       translations/mo/bs-ng-wizard-de.mo:${LOCALE_DIR}/de/LC_MESSAGES/bs-ng-wizard.mo
	       translations/mo/bs-ng-es.mo:${LOCALEDIR}/es/LC_MESSAGES/bashstyle-ng.mo
	       translations/mo/nx-rc-es.mo:${LOCALEDIR}/es/LC_MESSAGES/nx-rc.mo
	       translations/mo/bs-ng-it.mo:${LOCALEDIR}/it/LC_MESSAGES/bashstyle-ng.mo
	       translations/mo/bs-ng-ru.mo:${LOCALEDIR}/ru/LC_MESSAGES/bashstyle-ng.mo )

DOC_FILES=( documentation/*.html:${DOCDIR}
	    documentation/img/*.png:${DOCDIR}/img
	    documentation/img-style/*.png:${DOCDIR}/img-style
	    {AUTHORS,COPYING.CODE,COPYING.ICONS,CREDITS,NEWS,README}:${DOCDIR} )

BIN_FILES=( data/bashstyle:${BINDIR}
	    rc/bin/*:${DATADIR}/rc/bin )

PROFILE_FILES=( data/bashstyle.sh:${PROFILEDIR} )

ICON_FILES=( data/icons/*.png:${ICONDIR} )

PC_FILES=( data/bashstyle-ng.pc:${PCDIR} )
