#!/bin/bash

DATA_FILES=( ui/*.{py,ui}:${DATADIR}/ui
	     rc/nx-rc:${DATADIR}/rc
	     rc/ascii/*:${DATADIR}/rc/ascii
	     rc/dirinfo/*:${DATADIR}/rc/dirinfo
	     rc/functions/*:${DATADIR}/rc/functions
	     rc/internal/*:${DATADIR}/rc/internal
	     rc/settings/*:${DATADIR}/rc/settings
	     rc/styles/*:${DATADIR}/rc/styles
	     rc/wizard/*:${DATADIR}/rc/wizard
	     rc/generator/*:${DATADIR}/rc/generator
	     data/terminfo/b/*:${DATADIR}/terminfo/b
	     data/terminfo/m/*:${DATADIR}/terminfo/m
	     data/terminfo/n/*:${DATADIR}/terminfo/n
	     data/vim/colors/*:${DATADIR}/vim/colors )

LOCALE_FILES=( i18n/de/*.mo:${LOCALEDIR}/de/LC_MESSAGES/
	       i18n/es/*.mo:${LOCALEDIR}/es/LC_MESSAGES/
	       i18n/it/*.mo:${LOCALEDIR}/it/LC_MESSAGES/
	       i18n/ru/*.mo:${LOCALEDIR}/ru/LC_MESSAGES/ )

DOC_FILES=( documentation/*.html:${DOCDIR}
	    documentation/img/*.png:${DOCDIR}/img
	    documentation/img-style/*.png:${DOCDIR}/img-style
	    {AUTHORS,COPYING.CODE,COPYING.ICONS,CREDITS,NEWS,README}:${DOCDIR} )

BIN_FILES=( data/bashstyle:${BINDIR}
	    rc/bin/*:${DATADIR}/rc/bin )

PROFILE_FILES=( data/bashstyle.sh:${PROFILEDIR} )

ICON_FILES=( data/icons/*.png:${ICONDIR} )

PC_FILES=( data/bashstyle-ng.pc:${PCDIR} )

REMOVE_FILES=( ${LOCALEDIR}/{de,es,it,ru}/{bs-ng{,-wizard},nx-rc}.mo
	       ${BINDIR}/bashstyle
	       ${ICONDIR}/bs-ng*.png
	       ${PCDIR}/bashstyle-ng.pc
	       ${PROFILEDIR}/bashstyle.sh
	       ${DOCDIR}
	       ${DATADIR} )
