#!/bin/bash

start_message () {

	echo -e "\n${GREEN}BashStyle-NG${YELLOW} v${xVERSION} ${CYAN}${CODENAME}"
	tput sgr0

}

help_message () {

	echo -e "\n${GREEN}BashStyle-NG ${YELLOW}(make 0.99) ${CYAN}help"
	echo -e "\n${WHITE}Rules:\n"
	echo -e "${ORANGE}help${WHITE} |${GREEN} Display this help message\
	\n${ORANGE}pot${WHITE} |${GREEN} Generate .pot files\
	\n${ORANGE}po${WHITE} |${GREEN} Update .po files\
	\n${ORANGE}build${WHITE} |${GREEN} Build necessary files\
	\n${ORANGE}install${WHITE} |${GREEN} Install BashStyle-NG\
	\n${ORANGE}remove${WHITE} |${GREEN} Remove BashStyle-NG\
	\n${ORANGE}changelog${WHITE} |${GREEN} Generate ChangeLog" | column -t
	echo
	tput sgr0

}
