#!/bin/bash

installdirs ()
{

	mkdir -p $DESTDIR/$DATADIR
	for directory in ${DATADIR_LIST[@]}; do
		mkdir -p $DESTDIR/$DATADIR/$directory
	done

	mkdir -p $DESTDIR/$LOCALEDIR
	for directory in ${LOCALEDIR_LIST[@]}; do
		mkdir -p $DESTDIR/$LOCALEDIR/$directory/
	done

	mkdir -p $DESTDIR/$DOCDIR
	for directory in ${DOCDIR_LIST[@]}; do
		mkdir -p $DESTDIR/$DOCDIR/$directory
	done

	mkdir -p $DESTDIR/$BINDIR
	mkdir -p $DESTDIR/$PROFILEDIR
	mkdir -p $DESTDIR/$ICONDIR
	mkdir -p $DESTDIR/$PCDIR

}
