#!/bin/bash

inst ()
{

	case $1 in
		data )
			MODE=644
		;;

		bin )
			MODE=755
		;;
	esac

	shift

	FILE=${1/:*}
	DEST=${1/*:}

	install -m${MODE} ${FILE} ${DESTDIR}${DEST}

	unset FILE DEST

}

uninst ()
{

	xFILE=${1/:*}
	FILE=${xFILE/*\/}
	DEST=${1/*:}

	rm -f ${DESTDIR}${DEST}/${FILE}

	unset FILE DEST

}

install_bsng () {

	echo -e "${GREEN}Installing data files."
	for file in ${DATA_FILES[@]} ${LOCALE_FILES[@]} ${DOC_FILES[@]} \
	${PC_FILES[@]} ${ICON_FILES[@]}; do
		inst data "$file"
	done

	echo -e "${GREEN}Installing binary files."
	for file in ${PROFILE_FILES[@]} ${BIN_FILES[@]}; do
		inst bin "$file"
	done

}

remove_bsng () {

	echo -e "${RED}Removing all files."
	for file in ${DATA_FILES[@]} ${LOCALE_FILES[@]} ${DOC_FILES[@]} \
	${PC_FILES[@]} ${ICON_FILES[@]} ${PROFILE_FILES[@]} ${BIN_FILES[@]}; do
		uninst "$file"
	done

}
