#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2017 Christopher Bratusek		#
#							#
#########################################################

if [[ $(ini_get colored_ls) == True && $(ini_get enable_colors) == True ]]; then
	dbg_msg $"BashStyle-NG Setting:" Colored ls $"On"
	dbg_log alias ls="ls -CF --color=auto --group-directories-first"
else
	dbg_msg $"BashStyle-NG Setting:" Colored ls $"Off"
	dbg_log alias ls="ls -CF --color=no --group-directories-first"
fi

if [[ $(ini_get alias_one) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_one)"
	dbg_log alias "$(ini_get alias_one)"
fi

if [[ $(ini_get alias_two) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_two)"
	dbg_log alias "$(ini_get alias_two)"
fi

if [[ $(ini_get alias_three) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_three)"
	dbg_log alias "$(ini_get alias_three)"
fi

if [[ $(ini_get alias_four) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_four)"
	dbg_log alias "$(ini_get alias_four)"
fi

if [[ $(ini_get alias_five) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_five)"
	dbg_log alias "$(ini_get alias_five)"
fi

if [[ $(ini_get alias_six) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_six)"
	dbg_log alias "$(ini_get alias_six)"
fi

if [[ $(ini_get alias_seven) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_seven)"
	dbg_log alias "$(ini_get alias_seven)"
fi

if [[ $(ini_get alias_eight) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_eight)"
	dbg_log alias "$(ini_get alias_eight)"
fi

if [[ $(ini_get alias_nine) != "" ]]; then
	dbg_msg $"BashStyle-NG Setting:" Alias "$(ini_get alias_nine)"
	dbg_log alias "$(ini_get alias_nine)"
fi
