#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2015 Christopher Bratusek		#
# Copyright 2006 Philip Endecott			#
#							#
#########################################################

if [[ ! ${PROMPT_COMMAND} ]]; then

PROMPT_COMMAND () {
	cmd_text_colour='\[`tput setaf $((RANDOM%7))`\]'

	shopt -s promptvars

	PS1="${PS1}${cmd_text_colour}"
	PS2="${PS2}${cmd_text_colour}"
	PS3="${PS3}${cmd_text_colour}"
	PS4="${PS4}${cmd_text_colour}"

	if [[ $(ini_get colorshell_revert) == True ]]; then
		trap 'echo -ne "\e[0m"' DEBUG
	fi

	PRE_PROMPT_COMMAND

}

else

PRE_PROMPT_COMMAND () {
	cmd_text_colour='\[`tput setaf $((RANDOM%7))`\]'

	shopt -s promptvars

	PS1="${PS1}${cmd_text_colour}"
	PS2="${PS2}${cmd_text_colour}"
	PS3="${PS3}${cmd_text_colour}"
	PS4="${PS4}${cmd_text_colour}"

	if [[ $(ini_get colorshell_revert) == True ]]; then
		trap 'echo -ne "\e[0m"' DEBUG
	fi
}

fi
