#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2014 Christopher Bratusek		#
#							#
#########################################################

number=$(random 12)

case $number in

	0 ) pstyle=separator ;;
	1 ) pstyle=vector ;;
	2 ) pstyle=clock ;;
	3 ) pstyle=clock-ad ;;
	4 ) pstyle=elite ;;
	5 ) pstyle=poweruser ;;
	6 ) pstyle=dirks ;;
	7 ) pstyle=dot_prompt ;;
	8 ) pstyle=sepa_ng ;;
	9 ) pstyle=quirk ;;
	10 ) pstyle=sputnik ;;
	11 ) pstyle=ayoli ;;

esac
