#!/bin/bash
#########################################################
# 							#
# This is BashStyle-NG  				#
#							#
# Licensed under GNU GENERAL PUBLIC LICENSE v3    	#
#							#
# Copyright 2007 - 2010 Christopher Bratusek		#
#							#
#########################################################

number=$(random 15)

case $number in

	0 )
		pstyle=separator
	;;

	1 )
		pstyle=vector
	;;

	2 )
		pstyle=clock
	;;

	3 )
		pstyle=clock-ad
	;;

	4 )
		pstyle=dash
	;;

	5 )
		pstyle=job
	;;

	6 )
		pstyle=elite
	;;

	7 )
		pstyle=poweruser
	;;

	8 )
		pstyle=dirks
	;;

	9 )
		pstyle=minimal
	;;

	10 )
		pstyle=dot_prompt
	;;

	11 )
		pstyle=bracket
	;;

	12 )
		pstyle=sepa_ng
	;;

	13 )
		pstyle=quirk
	;;

	14 )
		pstyle=sputnik
	;;

esac
